// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface CancellationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.Cancellation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * consider adding an enum
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * consider adding an enum
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
