// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface FinishQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.FinishQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return Whether the queryId field is set.
   */
  boolean hasQueryId();
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return The queryId.
   */
  vastdb.queryengine.protocol.QueryId getQueryId();
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   */
  vastdb.queryengine.protocol.QueryIdOrBuilder getQueryIdOrBuilder();

  /**
   * <pre>
   * in case of premature cancellation
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 2;</code>
   * @return Whether the reason field is set.
   */
  boolean hasReason();
  /**
   * <pre>
   * in case of premature cancellation
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 2;</code>
   * @return The reason.
   */
  vastdb.queryengine.protocol.Cancellation getReason();
  /**
   * <pre>
   * in case of premature cancellation
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 2;</code>
   */
  vastdb.queryengine.protocol.CancellationOrBuilder getReasonOrBuilder();
}
