// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

/**
 * <pre>
 * client-&gt;worker (allows the server to free per-ticket resources)
 * </pre>
 *
 * Protobuf type {@code vastdb.queryengine.protocol.FinishDataRequest}
 */
public final class FinishDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vastdb.queryengine.protocol.FinishDataRequest)
    FinishDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FinishDataRequest.newBuilder() to construct.
  private FinishDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FinishDataRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FinishDataRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_FinishDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_FinishDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vastdb.queryengine.protocol.FinishDataRequest.class, vastdb.queryengine.protocol.FinishDataRequest.Builder.class);
  }

  private int bitField0_;
  public static final int QUERY_ID_FIELD_NUMBER = 1;
  private vastdb.queryengine.protocol.QueryId queryId_;
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return Whether the queryId field is set.
   */
  @java.lang.Override
  public boolean hasQueryId() {
    return queryId_ != null;
  }
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return The queryId.
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.QueryId getQueryId() {
    return queryId_ == null ? vastdb.queryengine.protocol.QueryId.getDefaultInstance() : queryId_;
  }
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.QueryIdOrBuilder getQueryIdOrBuilder() {
    return getQueryId();
  }

  public static final int TICKET_ID_FIELD_NUMBER = 5;
  private com.google.protobuf.Any ticketId_;
  /**
   * <code>.google.protobuf.Any ticket_id = 5;</code>
   * @return Whether the ticketId field is set.
   */
  @java.lang.Override
  public boolean hasTicketId() {
    return ticketId_ != null;
  }
  /**
   * <code>.google.protobuf.Any ticket_id = 5;</code>
   * @return The ticketId.
   */
  @java.lang.Override
  public com.google.protobuf.Any getTicketId() {
    return ticketId_ == null ? com.google.protobuf.Any.getDefaultInstance() : ticketId_;
  }
  /**
   * <code>.google.protobuf.Any ticket_id = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getTicketIdOrBuilder() {
    return getTicketId();
  }

  public static final int REASON_FIELD_NUMBER = 3;
  private vastdb.queryengine.protocol.Cancellation reason_;
  /**
   * <pre>
   * in case of premature cancellation
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
   * @return Whether the reason field is set.
   */
  @java.lang.Override
  public boolean hasReason() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * in case of premature cancellation
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
   * @return The reason.
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.Cancellation getReason() {
    return reason_ == null ? vastdb.queryengine.protocol.Cancellation.getDefaultInstance() : reason_;
  }
  /**
   * <pre>
   * in case of premature cancellation
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.CancellationOrBuilder getReasonOrBuilder() {
    return reason_ == null ? vastdb.queryengine.protocol.Cancellation.getDefaultInstance() : reason_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (queryId_ != null) {
      output.writeMessage(1, getQueryId());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getReason());
    }
    if (ticketId_ != null) {
      output.writeMessage(5, getTicketId());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (queryId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getQueryId());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getReason());
    }
    if (ticketId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTicketId());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vastdb.queryengine.protocol.FinishDataRequest)) {
      return super.equals(obj);
    }
    vastdb.queryengine.protocol.FinishDataRequest other = (vastdb.queryengine.protocol.FinishDataRequest) obj;

    if (hasQueryId() != other.hasQueryId()) return false;
    if (hasQueryId()) {
      if (!getQueryId()
          .equals(other.getQueryId())) return false;
    }
    if (hasTicketId() != other.hasTicketId()) return false;
    if (hasTicketId()) {
      if (!getTicketId()
          .equals(other.getTicketId())) return false;
    }
    if (hasReason() != other.hasReason()) return false;
    if (hasReason()) {
      if (!getReason()
          .equals(other.getReason())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasQueryId()) {
      hash = (37 * hash) + QUERY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getQueryId().hashCode();
    }
    if (hasTicketId()) {
      hash = (37 * hash) + TICKET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTicketId().hashCode();
    }
    if (hasReason()) {
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.FinishDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vastdb.queryengine.protocol.FinishDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * client-&gt;worker (allows the server to free per-ticket resources)
   * </pre>
   *
   * Protobuf type {@code vastdb.queryengine.protocol.FinishDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vastdb.queryengine.protocol.FinishDataRequest)
      vastdb.queryengine.protocol.FinishDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_FinishDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_FinishDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vastdb.queryengine.protocol.FinishDataRequest.class, vastdb.queryengine.protocol.FinishDataRequest.Builder.class);
    }

    // Construct using vastdb.queryengine.protocol.FinishDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReasonFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (queryIdBuilder_ == null) {
        queryId_ = null;
      } else {
        queryId_ = null;
        queryIdBuilder_ = null;
      }
      if (ticketIdBuilder_ == null) {
        ticketId_ = null;
      } else {
        ticketId_ = null;
        ticketIdBuilder_ = null;
      }
      if (reasonBuilder_ == null) {
        reason_ = null;
      } else {
        reasonBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_FinishDataRequest_descriptor;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.FinishDataRequest getDefaultInstanceForType() {
      return vastdb.queryengine.protocol.FinishDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.FinishDataRequest build() {
      vastdb.queryengine.protocol.FinishDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.FinishDataRequest buildPartial() {
      vastdb.queryengine.protocol.FinishDataRequest result = new vastdb.queryengine.protocol.FinishDataRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (queryIdBuilder_ == null) {
        result.queryId_ = queryId_;
      } else {
        result.queryId_ = queryIdBuilder_.build();
      }
      if (ticketIdBuilder_ == null) {
        result.ticketId_ = ticketId_;
      } else {
        result.ticketId_ = ticketIdBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (reasonBuilder_ == null) {
          result.reason_ = reason_;
        } else {
          result.reason_ = reasonBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vastdb.queryengine.protocol.FinishDataRequest) {
        return mergeFrom((vastdb.queryengine.protocol.FinishDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vastdb.queryengine.protocol.FinishDataRequest other) {
      if (other == vastdb.queryengine.protocol.FinishDataRequest.getDefaultInstance()) return this;
      if (other.hasQueryId()) {
        mergeQueryId(other.getQueryId());
      }
      if (other.hasTicketId()) {
        mergeTicketId(other.getTicketId());
      }
      if (other.hasReason()) {
        mergeReason(other.getReason());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getQueryIdFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 26: {
              input.readMessage(
                  getReasonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 26
            case 42: {
              input.readMessage(
                  getTicketIdFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private vastdb.queryengine.protocol.QueryId queryId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.QueryId, vastdb.queryengine.protocol.QueryId.Builder, vastdb.queryengine.protocol.QueryIdOrBuilder> queryIdBuilder_;
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     * @return Whether the queryId field is set.
     */
    public boolean hasQueryId() {
      return queryIdBuilder_ != null || queryId_ != null;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     * @return The queryId.
     */
    public vastdb.queryengine.protocol.QueryId getQueryId() {
      if (queryIdBuilder_ == null) {
        return queryId_ == null ? vastdb.queryengine.protocol.QueryId.getDefaultInstance() : queryId_;
      } else {
        return queryIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public Builder setQueryId(vastdb.queryengine.protocol.QueryId value) {
      if (queryIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        queryId_ = value;
        onChanged();
      } else {
        queryIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public Builder setQueryId(
        vastdb.queryengine.protocol.QueryId.Builder builderForValue) {
      if (queryIdBuilder_ == null) {
        queryId_ = builderForValue.build();
        onChanged();
      } else {
        queryIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public Builder mergeQueryId(vastdb.queryengine.protocol.QueryId value) {
      if (queryIdBuilder_ == null) {
        if (queryId_ != null) {
          queryId_ =
            vastdb.queryengine.protocol.QueryId.newBuilder(queryId_).mergeFrom(value).buildPartial();
        } else {
          queryId_ = value;
        }
        onChanged();
      } else {
        queryIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public Builder clearQueryId() {
      if (queryIdBuilder_ == null) {
        queryId_ = null;
        onChanged();
      } else {
        queryId_ = null;
        queryIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public vastdb.queryengine.protocol.QueryId.Builder getQueryIdBuilder() {
      
      onChanged();
      return getQueryIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public vastdb.queryengine.protocol.QueryIdOrBuilder getQueryIdOrBuilder() {
      if (queryIdBuilder_ != null) {
        return queryIdBuilder_.getMessageOrBuilder();
      } else {
        return queryId_ == null ?
            vastdb.queryengine.protocol.QueryId.getDefaultInstance() : queryId_;
      }
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.QueryId, vastdb.queryengine.protocol.QueryId.Builder, vastdb.queryengine.protocol.QueryIdOrBuilder> 
        getQueryIdFieldBuilder() {
      if (queryIdBuilder_ == null) {
        queryIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vastdb.queryengine.protocol.QueryId, vastdb.queryengine.protocol.QueryId.Builder, vastdb.queryengine.protocol.QueryIdOrBuilder>(
                getQueryId(),
                getParentForChildren(),
                isClean());
        queryId_ = null;
      }
      return queryIdBuilder_;
    }

    private com.google.protobuf.Any ticketId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> ticketIdBuilder_;
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     * @return Whether the ticketId field is set.
     */
    public boolean hasTicketId() {
      return ticketIdBuilder_ != null || ticketId_ != null;
    }
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     * @return The ticketId.
     */
    public com.google.protobuf.Any getTicketId() {
      if (ticketIdBuilder_ == null) {
        return ticketId_ == null ? com.google.protobuf.Any.getDefaultInstance() : ticketId_;
      } else {
        return ticketIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     */
    public Builder setTicketId(com.google.protobuf.Any value) {
      if (ticketIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ticketId_ = value;
        onChanged();
      } else {
        ticketIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     */
    public Builder setTicketId(
        com.google.protobuf.Any.Builder builderForValue) {
      if (ticketIdBuilder_ == null) {
        ticketId_ = builderForValue.build();
        onChanged();
      } else {
        ticketIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     */
    public Builder mergeTicketId(com.google.protobuf.Any value) {
      if (ticketIdBuilder_ == null) {
        if (ticketId_ != null) {
          ticketId_ =
            com.google.protobuf.Any.newBuilder(ticketId_).mergeFrom(value).buildPartial();
        } else {
          ticketId_ = value;
        }
        onChanged();
      } else {
        ticketIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     */
    public Builder clearTicketId() {
      if (ticketIdBuilder_ == null) {
        ticketId_ = null;
        onChanged();
      } else {
        ticketId_ = null;
        ticketIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     */
    public com.google.protobuf.Any.Builder getTicketIdBuilder() {
      
      onChanged();
      return getTicketIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getTicketIdOrBuilder() {
      if (ticketIdBuilder_ != null) {
        return ticketIdBuilder_.getMessageOrBuilder();
      } else {
        return ticketId_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : ticketId_;
      }
    }
    /**
     * <code>.google.protobuf.Any ticket_id = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getTicketIdFieldBuilder() {
      if (ticketIdBuilder_ == null) {
        ticketIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getTicketId(),
                getParentForChildren(),
                isClean());
        ticketId_ = null;
      }
      return ticketIdBuilder_;
    }

    private vastdb.queryengine.protocol.Cancellation reason_;
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.Cancellation, vastdb.queryengine.protocol.Cancellation.Builder, vastdb.queryengine.protocol.CancellationOrBuilder> reasonBuilder_;
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     * @return Whether the reason field is set.
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     * @return The reason.
     */
    public vastdb.queryengine.protocol.Cancellation getReason() {
      if (reasonBuilder_ == null) {
        return reason_ == null ? vastdb.queryengine.protocol.Cancellation.getDefaultInstance() : reason_;
      } else {
        return reasonBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     */
    public Builder setReason(vastdb.queryengine.protocol.Cancellation value) {
      if (reasonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reason_ = value;
        onChanged();
      } else {
        reasonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     */
    public Builder setReason(
        vastdb.queryengine.protocol.Cancellation.Builder builderForValue) {
      if (reasonBuilder_ == null) {
        reason_ = builderForValue.build();
        onChanged();
      } else {
        reasonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     */
    public Builder mergeReason(vastdb.queryengine.protocol.Cancellation value) {
      if (reasonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            reason_ != null &&
            reason_ != vastdb.queryengine.protocol.Cancellation.getDefaultInstance()) {
          reason_ =
            vastdb.queryengine.protocol.Cancellation.newBuilder(reason_).mergeFrom(value).buildPartial();
        } else {
          reason_ = value;
        }
        onChanged();
      } else {
        reasonBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     */
    public Builder clearReason() {
      if (reasonBuilder_ == null) {
        reason_ = null;
        onChanged();
      } else {
        reasonBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     */
    public vastdb.queryengine.protocol.Cancellation.Builder getReasonBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getReasonFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     */
    public vastdb.queryengine.protocol.CancellationOrBuilder getReasonOrBuilder() {
      if (reasonBuilder_ != null) {
        return reasonBuilder_.getMessageOrBuilder();
      } else {
        return reason_ == null ?
            vastdb.queryengine.protocol.Cancellation.getDefaultInstance() : reason_;
      }
    }
    /**
     * <pre>
     * in case of premature cancellation
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Cancellation reason = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.Cancellation, vastdb.queryengine.protocol.Cancellation.Builder, vastdb.queryengine.protocol.CancellationOrBuilder> 
        getReasonFieldBuilder() {
      if (reasonBuilder_ == null) {
        reasonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vastdb.queryengine.protocol.Cancellation, vastdb.queryengine.protocol.Cancellation.Builder, vastdb.queryengine.protocol.CancellationOrBuilder>(
                getReason(),
                getParentForChildren(),
                isClean());
        reason_ = null;
      }
      return reasonBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vastdb.queryengine.protocol.FinishDataRequest)
  }

  // @@protoc_insertion_point(class_scope:vastdb.queryengine.protocol.FinishDataRequest)
  private static final vastdb.queryengine.protocol.FinishDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vastdb.queryengine.protocol.FinishDataRequest();
  }

  public static vastdb.queryengine.protocol.FinishDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FinishDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<FinishDataRequest>() {
    @java.lang.Override
    public FinishDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FinishDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FinishDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vastdb.queryengine.protocol.FinishDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

