// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

/**
 * <pre>
 * worker-&gt;client: multiple responses from a specific endpoint, as a chunked response
 * This message will be followed (concatenated) by a stream of serialized Arrow `RecordBatch` objects,
 * using https://arrow.apache.org/docs/format/Columnar.html#encapsulated-message-format encoding.
 * Arrow schema is not sent here, since all batches across all tickets share the same schema
 * but as part of `StartQueryResponse` message.
 * the size of the message will be passed by the `tabular-protobuf-size` HTTP header
 * </pre>
 *
 * Protobuf type {@code vastdb.queryengine.protocol.GetDataResponse}
 */
public final class GetDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vastdb.queryengine.protocol.GetDataResponse)
    GetDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetDataResponse.newBuilder() to construct.
  private GetDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetDataResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetDataResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_GetDataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_GetDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vastdb.queryengine.protocol.GetDataResponse.class, vastdb.queryengine.protocol.GetDataResponse.Builder.class);
  }

  private int bitField0_;
  public static final int NEXT_FIELD_NUMBER = 1;
  private vastdb.queryengine.protocol.Offset next_;
  /**
   * <pre>
   * next is unset, if there is no more data available
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
   * @return Whether the next field is set.
   */
  @java.lang.Override
  public boolean hasNext() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * next is unset, if there is no more data available
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
   * @return The next.
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.Offset getNext() {
    return next_ == null ? vastdb.queryengine.protocol.Offset.getDefaultInstance() : next_;
  }
  /**
   * <pre>
   * next is unset, if there is no more data available
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.OffsetOrBuilder getNextOrBuilder() {
    return next_ == null ? vastdb.queryengine.protocol.Offset.getDefaultInstance() : next_;
  }

  public static final int EMPTY_STREAM_FIELD_NUMBER = 2;
  private boolean emptyStream_;
  /**
   * <code>optional bool empty_stream = 2;</code>
   * @return Whether the emptyStream field is set.
   */
  @java.lang.Override
  public boolean hasEmptyStream() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bool empty_stream = 2;</code>
   * @return The emptyStream.
   */
  @java.lang.Override
  public boolean getEmptyStream() {
    return emptyStream_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getNext());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, emptyStream_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNext());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, emptyStream_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vastdb.queryengine.protocol.GetDataResponse)) {
      return super.equals(obj);
    }
    vastdb.queryengine.protocol.GetDataResponse other = (vastdb.queryengine.protocol.GetDataResponse) obj;

    if (hasNext() != other.hasNext()) return false;
    if (hasNext()) {
      if (!getNext()
          .equals(other.getNext())) return false;
    }
    if (hasEmptyStream() != other.hasEmptyStream()) return false;
    if (hasEmptyStream()) {
      if (getEmptyStream()
          != other.getEmptyStream()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNext()) {
      hash = (37 * hash) + NEXT_FIELD_NUMBER;
      hash = (53 * hash) + getNext().hashCode();
    }
    if (hasEmptyStream()) {
      hash = (37 * hash) + EMPTY_STREAM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEmptyStream());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.GetDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vastdb.queryengine.protocol.GetDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * worker-&gt;client: multiple responses from a specific endpoint, as a chunked response
   * This message will be followed (concatenated) by a stream of serialized Arrow `RecordBatch` objects,
   * using https://arrow.apache.org/docs/format/Columnar.html#encapsulated-message-format encoding.
   * Arrow schema is not sent here, since all batches across all tickets share the same schema
   * but as part of `StartQueryResponse` message.
   * the size of the message will be passed by the `tabular-protobuf-size` HTTP header
   * </pre>
   *
   * Protobuf type {@code vastdb.queryengine.protocol.GetDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vastdb.queryengine.protocol.GetDataResponse)
      vastdb.queryengine.protocol.GetDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_GetDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_GetDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vastdb.queryengine.protocol.GetDataResponse.class, vastdb.queryengine.protocol.GetDataResponse.Builder.class);
    }

    // Construct using vastdb.queryengine.protocol.GetDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (nextBuilder_ == null) {
        next_ = null;
      } else {
        nextBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      emptyStream_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_GetDataResponse_descriptor;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.GetDataResponse getDefaultInstanceForType() {
      return vastdb.queryengine.protocol.GetDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.GetDataResponse build() {
      vastdb.queryengine.protocol.GetDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.GetDataResponse buildPartial() {
      vastdb.queryengine.protocol.GetDataResponse result = new vastdb.queryengine.protocol.GetDataResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (nextBuilder_ == null) {
          result.next_ = next_;
        } else {
          result.next_ = nextBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.emptyStream_ = emptyStream_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vastdb.queryengine.protocol.GetDataResponse) {
        return mergeFrom((vastdb.queryengine.protocol.GetDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vastdb.queryengine.protocol.GetDataResponse other) {
      if (other == vastdb.queryengine.protocol.GetDataResponse.getDefaultInstance()) return this;
      if (other.hasNext()) {
        mergeNext(other.getNext());
      }
      if (other.hasEmptyStream()) {
        setEmptyStream(other.getEmptyStream());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getNextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              emptyStream_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private vastdb.queryengine.protocol.Offset next_;
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.Offset, vastdb.queryengine.protocol.Offset.Builder, vastdb.queryengine.protocol.OffsetOrBuilder> nextBuilder_;
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     * @return Whether the next field is set.
     */
    public boolean hasNext() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     * @return The next.
     */
    public vastdb.queryengine.protocol.Offset getNext() {
      if (nextBuilder_ == null) {
        return next_ == null ? vastdb.queryengine.protocol.Offset.getDefaultInstance() : next_;
      } else {
        return nextBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     */
    public Builder setNext(vastdb.queryengine.protocol.Offset value) {
      if (nextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        next_ = value;
        onChanged();
      } else {
        nextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     */
    public Builder setNext(
        vastdb.queryengine.protocol.Offset.Builder builderForValue) {
      if (nextBuilder_ == null) {
        next_ = builderForValue.build();
        onChanged();
      } else {
        nextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     */
    public Builder mergeNext(vastdb.queryengine.protocol.Offset value) {
      if (nextBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            next_ != null &&
            next_ != vastdb.queryengine.protocol.Offset.getDefaultInstance()) {
          next_ =
            vastdb.queryengine.protocol.Offset.newBuilder(next_).mergeFrom(value).buildPartial();
        } else {
          next_ = value;
        }
        onChanged();
      } else {
        nextBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     */
    public Builder clearNext() {
      if (nextBuilder_ == null) {
        next_ = null;
        onChanged();
      } else {
        nextBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     */
    public vastdb.queryengine.protocol.Offset.Builder getNextBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getNextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     */
    public vastdb.queryengine.protocol.OffsetOrBuilder getNextOrBuilder() {
      if (nextBuilder_ != null) {
        return nextBuilder_.getMessageOrBuilder();
      } else {
        return next_ == null ?
            vastdb.queryengine.protocol.Offset.getDefaultInstance() : next_;
      }
    }
    /**
     * <pre>
     * next is unset, if there is no more data available
     * </pre>
     *
     * <code>optional .vastdb.queryengine.protocol.Offset next = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.Offset, vastdb.queryengine.protocol.Offset.Builder, vastdb.queryengine.protocol.OffsetOrBuilder> 
        getNextFieldBuilder() {
      if (nextBuilder_ == null) {
        nextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vastdb.queryengine.protocol.Offset, vastdb.queryengine.protocol.Offset.Builder, vastdb.queryengine.protocol.OffsetOrBuilder>(
                getNext(),
                getParentForChildren(),
                isClean());
        next_ = null;
      }
      return nextBuilder_;
    }

    private boolean emptyStream_ ;
    /**
     * <code>optional bool empty_stream = 2;</code>
     * @return Whether the emptyStream field is set.
     */
    @java.lang.Override
    public boolean hasEmptyStream() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool empty_stream = 2;</code>
     * @return The emptyStream.
     */
    @java.lang.Override
    public boolean getEmptyStream() {
      return emptyStream_;
    }
    /**
     * <code>optional bool empty_stream = 2;</code>
     * @param value The emptyStream to set.
     * @return This builder for chaining.
     */
    public Builder setEmptyStream(boolean value) {
      bitField0_ |= 0x00000002;
      emptyStream_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool empty_stream = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmptyStream() {
      bitField0_ = (bitField0_ & ~0x00000002);
      emptyStream_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vastdb.queryengine.protocol.GetDataResponse)
  }

  // @@protoc_insertion_point(class_scope:vastdb.queryengine.protocol.GetDataResponse)
  private static final vastdb.queryengine.protocol.GetDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vastdb.queryengine.protocol.GetDataResponse();
  }

  public static vastdb.queryengine.protocol.GetDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetDataResponse>() {
    @java.lang.Override
    public GetDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vastdb.queryengine.protocol.GetDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

