// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface GetDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.GetDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return Whether the queryId field is set.
   */
  boolean hasQueryId();
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return The queryId.
   */
  vastdb.queryengine.protocol.QueryId getQueryId();
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   */
  vastdb.queryengine.protocol.QueryIdOrBuilder getQueryIdOrBuilder();

  /**
   * <code>.google.protobuf.Any ticket_id = 7;</code>
   * @return Whether the ticketId field is set.
   */
  boolean hasTicketId();
  /**
   * <code>.google.protobuf.Any ticket_id = 7;</code>
   * @return The ticketId.
   */
  com.google.protobuf.Any getTicketId();
  /**
   * <code>.google.protobuf.Any ticket_id = 7;</code>
   */
  com.google.protobuf.AnyOrBuilder getTicketIdOrBuilder();

  /**
   * <pre>
   * ACKs all previous offsets, set on subsequent requests for pagination
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Offset offset = 3;</code>
   * @return Whether the offset field is set.
   */
  boolean hasOffset();
  /**
   * <pre>
   * ACKs all previous offsets, set on subsequent requests for pagination
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Offset offset = 3;</code>
   * @return The offset.
   */
  vastdb.queryengine.protocol.Offset getOffset();
  /**
   * <pre>
   * ACKs all previous offsets, set on subsequent requests for pagination
   * </pre>
   *
   * <code>optional .vastdb.queryengine.protocol.Offset offset = 3;</code>
   */
  vastdb.queryengine.protocol.OffsetOrBuilder getOffsetOrBuilder();

  /**
   * <pre>
   * for long-polling the server
   * </pre>
   *
   * <code>uint64 request_timeout_sec = 4;</code>
   * @return The requestTimeoutSec.
   */
  long getRequestTimeoutSec();

  /**
   * <pre>
   * in bytes (to prevent client OOM)
   * </pre>
   *
   * <code>optional uint64 response_size_hint = 5;</code>
   * @return Whether the responseSizeHint field is set.
   */
  boolean hasResponseSizeHint();
  /**
   * <pre>
   * in bytes (to prevent client OOM)
   * </pre>
   *
   * <code>optional uint64 response_size_hint = 5;</code>
   * @return The responseSizeHint.
   */
  long getResponseSizeHint();
}
