// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface ListQueriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.ListQueriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .vastdb.queryengine.protocol.QueryId query_ids = 1;</code>
   */
  java.util.List<vastdb.queryengine.protocol.QueryId> 
      getQueryIdsList();
  /**
   * <code>repeated .vastdb.queryengine.protocol.QueryId query_ids = 1;</code>
   */
  vastdb.queryengine.protocol.QueryId getQueryIds(int index);
  /**
   * <code>repeated .vastdb.queryengine.protocol.QueryId query_ids = 1;</code>
   */
  int getQueryIdsCount();
  /**
   * <code>repeated .vastdb.queryengine.protocol.QueryId query_ids = 1;</code>
   */
  java.util.List<? extends vastdb.queryengine.protocol.QueryIdOrBuilder> 
      getQueryIdsOrBuilderList();
  /**
   * <code>repeated .vastdb.queryengine.protocol.QueryId query_ids = 1;</code>
   */
  vastdb.queryengine.protocol.QueryIdOrBuilder getQueryIdsOrBuilder(
      int index);

  /**
   * <pre>
   * theres more queries in the server
   * </pre>
   *
   * <code>optional bool is_truncated = 2;</code>
   * @return Whether the isTruncated field is set.
   */
  boolean hasIsTruncated();
  /**
   * <pre>
   * theres more queries in the server
   * </pre>
   *
   * <code>optional bool is_truncated = 2;</code>
   * @return The isTruncated.
   */
  boolean getIsTruncated();
}
