// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface ListQueriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.ListQueriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * if not specified, return all
   * </pre>
   *
   * <code>optional uint64 start_time_sec = 1;</code>
   * @return Whether the startTimeSec field is set.
   */
  boolean hasStartTimeSec();
  /**
   * <pre>
   * if not specified, return all
   * </pre>
   *
   * <code>optional uint64 start_time_sec = 1;</code>
   * @return The startTimeSec.
   */
  long getStartTimeSec();

  /**
   * <pre>
   * limit response items
   * </pre>
   *
   * <code>optional uint32 max_entries = 2;</code>
   * @return Whether the maxEntries field is set.
   */
  boolean hasMaxEntries();
  /**
   * <pre>
   * limit response items
   * </pre>
   *
   * <code>optional uint32 max_entries = 2;</code>
   * @return The maxEntries.
   */
  int getMaxEntries();

  /**
   * <pre>
   * if set return only queries from this vip
   * </pre>
   *
   * <code>optional string vip = 3;</code>
   * @return Whether the vip field is set.
   */
  boolean hasVip();
  /**
   * <pre>
   * if set return only queries from this vip
   * </pre>
   *
   * <code>optional string vip = 3;</code>
   * @return The vip.
   */
  java.lang.String getVip();
  /**
   * <pre>
   * if set return only queries from this vip
   * </pre>
   *
   * <code>optional string vip = 3;</code>
   * @return The bytes for vip.
   */
  com.google.protobuf.ByteString
      getVipBytes();
}
