// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface MetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.Metric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.vastdb.queryengine.protocol.Namespace key = 1;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>.vastdb.queryengine.protocol.Namespace key = 1;</code>
   * @return The key.
   */
  vastdb.queryengine.protocol.Namespace getKey();
  /**
   * <code>.vastdb.queryengine.protocol.Namespace key = 1;</code>
   */
  vastdb.queryengine.protocol.NamespaceOrBuilder getKeyOrBuilder();

  /**
   * <pre>
   * rows / bytes / nanoseconds consumed
   * </pre>
   *
   * <code>uint64 counter = 2;</code>
   * @return Whether the counter field is set.
   */
  boolean hasCounter();
  /**
   * <pre>
   * rows / bytes / nanoseconds consumed
   * </pre>
   *
   * <code>uint64 counter = 2;</code>
   * @return The counter.
   */
  long getCounter();

  /**
   * <pre>
   * RAM usage / queue length
   * </pre>
   *
   * <code>uint64 gauge = 3;</code>
   * @return Whether the gauge field is set.
   */
  boolean hasGauge();
  /**
   * <pre>
   * RAM usage / queue length
   * </pre>
   *
   * <code>uint64 gauge = 3;</code>
   * @return The gauge.
   */
  long getGauge();

  /**
   * <pre>
   * request latency (e.g. using https://github.com/tdunning/t-digest)
   * </pre>
   *
   * <code>bytes histogram = 4;</code>
   * @return Whether the histogram field is set.
   */
  boolean hasHistogram();
  /**
   * <pre>
   * request latency (e.g. using https://github.com/tdunning/t-digest)
   * </pre>
   *
   * <code>bytes histogram = 4;</code>
   * @return The histogram.
   */
  com.google.protobuf.ByteString getHistogram();

  /**
   * <pre>
   * when the measurement was done
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 5;</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <pre>
   * when the measurement was done
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 5;</code>
   * @return The time.
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <pre>
   * when the measurement was done
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

  public vastdb.queryengine.protocol.Metric.ValueCase getValueCase();
}
