// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface NamespaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.Namespace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * for namespacing/tagging
   * </pre>
   *
   * <code>repeated string name = 1;</code>
   * @return A list containing the name.
   */
  java.util.List<java.lang.String>
      getNameList();
  /**
   * <pre>
   * for namespacing/tagging
   * </pre>
   *
   * <code>repeated string name = 1;</code>
   * @return The count of name.
   */
  int getNameCount();
  /**
   * <pre>
   * for namespacing/tagging
   * </pre>
   *
   * <code>repeated string name = 1;</code>
   * @param index The index of the element to return.
   * @return The name at the given index.
   */
  java.lang.String getName(int index);
  /**
   * <pre>
   * for namespacing/tagging
   * </pre>
   *
   * <code>repeated string name = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the name at the given index.
   */
  com.google.protobuf.ByteString
      getNameBytes(int index);
}
