// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface OffsetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.Offset)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ordered by output `RecordBatch` queue
   * </pre>
   *
   * <code>uint64 record_batch_id = 1;</code>
   * @return The recordBatchId.
   */
  long getRecordBatchId();
}
