// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

/**
 * Protobuf type {@code vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse}
 */
public final class QueryEngineGetCapabilitiesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse)
    QueryEngineGetCapabilitiesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryEngineGetCapabilitiesResponse.newBuilder() to construct.
  private QueryEngineGetCapabilitiesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryEngineGetCapabilitiesResponse() {
    serverVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueryEngineGetCapabilitiesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse.class, vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse.Builder.class);
  }

  public static final int SERVER_VERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object serverVersion_;
  /**
   * <code>string server_version = 1;</code>
   * @return The serverVersion.
   */
  @java.lang.Override
  public java.lang.String getServerVersion() {
    java.lang.Object ref = serverVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string server_version = 1;</code>
   * @return The bytes for serverVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerVersionBytes() {
    java.lang.Object ref = serverVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_OPTIONS_SUPPORT_FIELD_NUMBER = 2;
  private boolean sessionOptionsSupport_;
  /**
   * <code>bool session_options_support = 2;</code>
   * @return The sessionOptionsSupport.
   */
  @java.lang.Override
  public boolean getSessionOptionsSupport() {
    return sessionOptionsSupport_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverVersion_);
    }
    if (sessionOptionsSupport_ != false) {
      output.writeBool(2, sessionOptionsSupport_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverVersion_);
    }
    if (sessionOptionsSupport_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, sessionOptionsSupport_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse)) {
      return super.equals(obj);
    }
    vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse other = (vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse) obj;

    if (!getServerVersion()
        .equals(other.getServerVersion())) return false;
    if (getSessionOptionsSupport()
        != other.getSessionOptionsSupport()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVER_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getServerVersion().hashCode();
    hash = (37 * hash) + SESSION_OPTIONS_SUPPORT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSessionOptionsSupport());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse)
      vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse.class, vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse.Builder.class);
    }

    // Construct using vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serverVersion_ = "";

      sessionOptionsSupport_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_descriptor;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse getDefaultInstanceForType() {
      return vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse build() {
      vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse buildPartial() {
      vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse result = new vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse(this);
      result.serverVersion_ = serverVersion_;
      result.sessionOptionsSupport_ = sessionOptionsSupport_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse) {
        return mergeFrom((vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse other) {
      if (other == vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse.getDefaultInstance()) return this;
      if (!other.getServerVersion().isEmpty()) {
        serverVersion_ = other.serverVersion_;
        onChanged();
      }
      if (other.getSessionOptionsSupport() != false) {
        setSessionOptionsSupport(other.getSessionOptionsSupport());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              serverVersion_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              sessionOptionsSupport_ = input.readBool();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object serverVersion_ = "";
    /**
     * <code>string server_version = 1;</code>
     * @return The serverVersion.
     */
    public java.lang.String getServerVersion() {
      java.lang.Object ref = serverVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string server_version = 1;</code>
     * @return The bytes for serverVersion.
     */
    public com.google.protobuf.ByteString
        getServerVersionBytes() {
      java.lang.Object ref = serverVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string server_version = 1;</code>
     * @param value The serverVersion to set.
     * @return This builder for chaining.
     */
    public Builder setServerVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string server_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerVersion() {
      
      serverVersion_ = getDefaultInstance().getServerVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string server_version = 1;</code>
     * @param value The bytes for serverVersion to set.
     * @return This builder for chaining.
     */
    public Builder setServerVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverVersion_ = value;
      onChanged();
      return this;
    }

    private boolean sessionOptionsSupport_ ;
    /**
     * <code>bool session_options_support = 2;</code>
     * @return The sessionOptionsSupport.
     */
    @java.lang.Override
    public boolean getSessionOptionsSupport() {
      return sessionOptionsSupport_;
    }
    /**
     * <code>bool session_options_support = 2;</code>
     * @param value The sessionOptionsSupport to set.
     * @return This builder for chaining.
     */
    public Builder setSessionOptionsSupport(boolean value) {
      
      sessionOptionsSupport_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool session_options_support = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionOptionsSupport() {
      
      sessionOptionsSupport_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse)
  }

  // @@protoc_insertion_point(class_scope:vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse)
  private static final vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse();
  }

  public static vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryEngineGetCapabilitiesResponse>
      PARSER = new com.google.protobuf.AbstractParser<QueryEngineGetCapabilitiesResponse>() {
    @java.lang.Override
    public QueryEngineGetCapabilitiesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QueryEngineGetCapabilitiesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryEngineGetCapabilitiesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vastdb.queryengine.protocol.QueryEngineGetCapabilitiesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

