// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface QueryStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.QueryStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return Whether the queryId field is set.
   */
  boolean hasQueryId();
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return The queryId.
   */
  vastdb.queryengine.protocol.QueryId getQueryId();
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   */
  vastdb.queryengine.protocol.QueryIdOrBuilder getQueryIdOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  java.util.List<vastdb.queryengine.protocol.Metric> 
      getMetricsList();
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  vastdb.queryengine.protocol.Metric getMetrics(int index);
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  int getMetricsCount();
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  java.util.List<? extends vastdb.queryengine.protocol.MetricOrBuilder> 
      getMetricsOrBuilderList();
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  vastdb.queryengine.protocol.MetricOrBuilder getMetricsOrBuilder(
      int index);

  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  java.util.List<vastdb.queryengine.protocol.Ticket> 
      getTicketsList();
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  vastdb.queryengine.protocol.Ticket getTickets(int index);
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  int getTicketsCount();
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  java.util.List<? extends vastdb.queryengine.protocol.TicketOrBuilder> 
      getTicketsOrBuilderList();
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  vastdb.queryengine.protocol.TicketOrBuilder getTicketsOrBuilder(
      int index);

  /**
   * <code>optional uint32 status_code = 5;</code>
   * @return Whether the statusCode field is set.
   */
  boolean hasStatusCode();
  /**
   * <code>optional uint32 status_code = 5;</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <code>optional string description = 6;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 6;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 6;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional uint32 state = 7;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>optional uint32 state = 7;</code>
   * @return The state.
   */
  int getState();
}
