// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface QueryIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.QueryId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 req_id = 1;</code>
   * @return The reqId.
   */
  long getReqId();

  /**
   * <code>uint64 vip_id = 2;</code>
   * @return The vipId.
   */
  long getVipId();
}
