// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

/**
 * Protobuf type {@code vastdb.queryengine.protocol.QueryStatus}
 */
public final class QueryStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vastdb.queryengine.protocol.QueryStatus)
    QueryStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryStatus.newBuilder() to construct.
  private QueryStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryStatus() {
    metrics_ = java.util.Collections.emptyList();
    tickets_ = java.util.Collections.emptyList();
    description_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueryStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vastdb.queryengine.protocol.QueryStatus.class, vastdb.queryengine.protocol.QueryStatus.Builder.class);
  }

  private int bitField0_;
  public static final int QUERY_ID_FIELD_NUMBER = 1;
  private vastdb.queryengine.protocol.QueryId queryId_;
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return Whether the queryId field is set.
   */
  @java.lang.Override
  public boolean hasQueryId() {
    return queryId_ != null;
  }
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   * @return The queryId.
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.QueryId getQueryId() {
    return queryId_ == null ? vastdb.queryengine.protocol.QueryId.getDefaultInstance() : queryId_;
  }
  /**
   * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.QueryIdOrBuilder getQueryIdOrBuilder() {
    return getQueryId();
  }

  public static final int START_TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp startTime_;
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   * @return Whether the startTime field is set.
   */
  @java.lang.Override
  public boolean hasStartTime() {
    return startTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getStartTime() {
    return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder() {
    return getStartTime();
  }

  public static final int METRICS_FIELD_NUMBER = 3;
  private java.util.List<vastdb.queryengine.protocol.Metric> metrics_;
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  @java.lang.Override
  public java.util.List<vastdb.queryengine.protocol.Metric> getMetricsList() {
    return metrics_;
  }
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends vastdb.queryengine.protocol.MetricOrBuilder> 
      getMetricsOrBuilderList() {
    return metrics_;
  }
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  @java.lang.Override
  public int getMetricsCount() {
    return metrics_.size();
  }
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.Metric getMetrics(int index) {
    return metrics_.get(index);
  }
  /**
   * <pre>
   * updated during query execution
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.MetricOrBuilder getMetricsOrBuilder(
      int index) {
    return metrics_.get(index);
  }

  public static final int TICKETS_FIELD_NUMBER = 4;
  private java.util.List<vastdb.queryengine.protocol.Ticket> tickets_;
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  @java.lang.Override
  public java.util.List<vastdb.queryengine.protocol.Ticket> getTicketsList() {
    return tickets_;
  }
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends vastdb.queryengine.protocol.TicketOrBuilder> 
      getTicketsOrBuilderList() {
    return tickets_;
  }
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  @java.lang.Override
  public int getTicketsCount() {
    return tickets_.size();
  }
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.Ticket getTickets(int index) {
    return tickets_.get(index);
  }
  /**
   * <pre>
   * # of tickets must not change between responses
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.TicketOrBuilder getTicketsOrBuilder(
      int index) {
    return tickets_.get(index);
  }

  public static final int STATUS_CODE_FIELD_NUMBER = 5;
  private int statusCode_;
  /**
   * <code>optional uint32 status_code = 5;</code>
   * @return Whether the statusCode field is set.
   */
  @java.lang.Override
  public boolean hasStatusCode() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint32 status_code = 5;</code>
   * @return The statusCode.
   */
  @java.lang.Override
  public int getStatusCode() {
    return statusCode_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 6;
  private volatile java.lang.Object description_;
  /**
   * <code>optional string description = 6;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string description = 6;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>optional string description = 6;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_FIELD_NUMBER = 7;
  private int state_;
  /**
   * <code>optional uint32 state = 7;</code>
   * @return Whether the state field is set.
   */
  @java.lang.Override
  public boolean hasState() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint32 state = 7;</code>
   * @return The state.
   */
  @java.lang.Override
  public int getState() {
    return state_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (queryId_ != null) {
      output.writeMessage(1, getQueryId());
    }
    if (startTime_ != null) {
      output.writeMessage(2, getStartTime());
    }
    for (int i = 0; i < metrics_.size(); i++) {
      output.writeMessage(3, metrics_.get(i));
    }
    for (int i = 0; i < tickets_.size(); i++) {
      output.writeMessage(4, tickets_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(5, statusCode_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, description_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(7, state_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (queryId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getQueryId());
    }
    if (startTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStartTime());
    }
    for (int i = 0; i < metrics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, metrics_.get(i));
    }
    for (int i = 0; i < tickets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, tickets_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, statusCode_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, description_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, state_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vastdb.queryengine.protocol.QueryStatus)) {
      return super.equals(obj);
    }
    vastdb.queryengine.protocol.QueryStatus other = (vastdb.queryengine.protocol.QueryStatus) obj;

    if (hasQueryId() != other.hasQueryId()) return false;
    if (hasQueryId()) {
      if (!getQueryId()
          .equals(other.getQueryId())) return false;
    }
    if (hasStartTime() != other.hasStartTime()) return false;
    if (hasStartTime()) {
      if (!getStartTime()
          .equals(other.getStartTime())) return false;
    }
    if (!getMetricsList()
        .equals(other.getMetricsList())) return false;
    if (!getTicketsList()
        .equals(other.getTicketsList())) return false;
    if (hasStatusCode() != other.hasStatusCode()) return false;
    if (hasStatusCode()) {
      if (getStatusCode()
          != other.getStatusCode()) return false;
    }
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (hasState() != other.hasState()) return false;
    if (hasState()) {
      if (getState()
          != other.getState()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasQueryId()) {
      hash = (37 * hash) + QUERY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getQueryId().hashCode();
    }
    if (hasStartTime()) {
      hash = (37 * hash) + START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
    }
    if (getMetricsCount() > 0) {
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getMetricsList().hashCode();
    }
    if (getTicketsCount() > 0) {
      hash = (37 * hash) + TICKETS_FIELD_NUMBER;
      hash = (53 * hash) + getTicketsList().hashCode();
    }
    if (hasStatusCode()) {
      hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    if (hasState()) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vastdb.queryengine.protocol.QueryStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.QueryStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vastdb.queryengine.protocol.QueryStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vastdb.queryengine.protocol.QueryStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vastdb.queryengine.protocol.QueryStatus)
      vastdb.queryengine.protocol.QueryStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vastdb.queryengine.protocol.QueryStatus.class, vastdb.queryengine.protocol.QueryStatus.Builder.class);
    }

    // Construct using vastdb.queryengine.protocol.QueryStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (queryIdBuilder_ == null) {
        queryId_ = null;
      } else {
        queryId_ = null;
        queryIdBuilder_ = null;
      }
      if (startTimeBuilder_ == null) {
        startTime_ = null;
      } else {
        startTime_ = null;
        startTimeBuilder_ = null;
      }
      if (metricsBuilder_ == null) {
        metrics_ = java.util.Collections.emptyList();
      } else {
        metrics_ = null;
        metricsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (ticketsBuilder_ == null) {
        tickets_ = java.util.Collections.emptyList();
      } else {
        tickets_ = null;
        ticketsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      statusCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      description_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      state_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_QueryStatus_descriptor;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.QueryStatus getDefaultInstanceForType() {
      return vastdb.queryengine.protocol.QueryStatus.getDefaultInstance();
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.QueryStatus build() {
      vastdb.queryengine.protocol.QueryStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.QueryStatus buildPartial() {
      vastdb.queryengine.protocol.QueryStatus result = new vastdb.queryengine.protocol.QueryStatus(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (queryIdBuilder_ == null) {
        result.queryId_ = queryId_;
      } else {
        result.queryId_ = queryIdBuilder_.build();
      }
      if (startTimeBuilder_ == null) {
        result.startTime_ = startTime_;
      } else {
        result.startTime_ = startTimeBuilder_.build();
      }
      if (metricsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          metrics_ = java.util.Collections.unmodifiableList(metrics_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.metrics_ = metrics_;
      } else {
        result.metrics_ = metricsBuilder_.build();
      }
      if (ticketsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          tickets_ = java.util.Collections.unmodifiableList(tickets_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.tickets_ = tickets_;
      } else {
        result.tickets_ = ticketsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.statusCode_ = statusCode_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.description_ = description_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.state_ = state_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vastdb.queryengine.protocol.QueryStatus) {
        return mergeFrom((vastdb.queryengine.protocol.QueryStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vastdb.queryengine.protocol.QueryStatus other) {
      if (other == vastdb.queryengine.protocol.QueryStatus.getDefaultInstance()) return this;
      if (other.hasQueryId()) {
        mergeQueryId(other.getQueryId());
      }
      if (other.hasStartTime()) {
        mergeStartTime(other.getStartTime());
      }
      if (metricsBuilder_ == null) {
        if (!other.metrics_.isEmpty()) {
          if (metrics_.isEmpty()) {
            metrics_ = other.metrics_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMetricsIsMutable();
            metrics_.addAll(other.metrics_);
          }
          onChanged();
        }
      } else {
        if (!other.metrics_.isEmpty()) {
          if (metricsBuilder_.isEmpty()) {
            metricsBuilder_.dispose();
            metricsBuilder_ = null;
            metrics_ = other.metrics_;
            bitField0_ = (bitField0_ & ~0x00000001);
            metricsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetricsFieldBuilder() : null;
          } else {
            metricsBuilder_.addAllMessages(other.metrics_);
          }
        }
      }
      if (ticketsBuilder_ == null) {
        if (!other.tickets_.isEmpty()) {
          if (tickets_.isEmpty()) {
            tickets_ = other.tickets_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTicketsIsMutable();
            tickets_.addAll(other.tickets_);
          }
          onChanged();
        }
      } else {
        if (!other.tickets_.isEmpty()) {
          if (ticketsBuilder_.isEmpty()) {
            ticketsBuilder_.dispose();
            ticketsBuilder_ = null;
            tickets_ = other.tickets_;
            bitField0_ = (bitField0_ & ~0x00000002);
            ticketsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTicketsFieldBuilder() : null;
          } else {
            ticketsBuilder_.addAllMessages(other.tickets_);
          }
        }
      }
      if (other.hasStatusCode()) {
        setStatusCode(other.getStatusCode());
      }
      if (other.hasDescription()) {
        bitField0_ |= 0x00000008;
        description_ = other.description_;
        onChanged();
      }
      if (other.hasState()) {
        setState(other.getState());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getQueryIdFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getStartTimeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 26: {
              vastdb.queryengine.protocol.Metric m =
                  input.readMessage(
                      vastdb.queryengine.protocol.Metric.parser(),
                      extensionRegistry);
              if (metricsBuilder_ == null) {
                ensureMetricsIsMutable();
                metrics_.add(m);
              } else {
                metricsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              vastdb.queryengine.protocol.Ticket m =
                  input.readMessage(
                      vastdb.queryengine.protocol.Ticket.parser(),
                      extensionRegistry);
              if (ticketsBuilder_ == null) {
                ensureTicketsIsMutable();
                tickets_.add(m);
              } else {
                ticketsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 40: {
              statusCode_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 40
            case 50: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 50
            case 56: {
              state_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private vastdb.queryengine.protocol.QueryId queryId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.QueryId, vastdb.queryengine.protocol.QueryId.Builder, vastdb.queryengine.protocol.QueryIdOrBuilder> queryIdBuilder_;
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     * @return Whether the queryId field is set.
     */
    public boolean hasQueryId() {
      return queryIdBuilder_ != null || queryId_ != null;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     * @return The queryId.
     */
    public vastdb.queryengine.protocol.QueryId getQueryId() {
      if (queryIdBuilder_ == null) {
        return queryId_ == null ? vastdb.queryengine.protocol.QueryId.getDefaultInstance() : queryId_;
      } else {
        return queryIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public Builder setQueryId(vastdb.queryengine.protocol.QueryId value) {
      if (queryIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        queryId_ = value;
        onChanged();
      } else {
        queryIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public Builder setQueryId(
        vastdb.queryengine.protocol.QueryId.Builder builderForValue) {
      if (queryIdBuilder_ == null) {
        queryId_ = builderForValue.build();
        onChanged();
      } else {
        queryIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public Builder mergeQueryId(vastdb.queryengine.protocol.QueryId value) {
      if (queryIdBuilder_ == null) {
        if (queryId_ != null) {
          queryId_ =
            vastdb.queryengine.protocol.QueryId.newBuilder(queryId_).mergeFrom(value).buildPartial();
        } else {
          queryId_ = value;
        }
        onChanged();
      } else {
        queryIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public Builder clearQueryId() {
      if (queryIdBuilder_ == null) {
        queryId_ = null;
        onChanged();
      } else {
        queryId_ = null;
        queryIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public vastdb.queryengine.protocol.QueryId.Builder getQueryIdBuilder() {
      
      onChanged();
      return getQueryIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    public vastdb.queryengine.protocol.QueryIdOrBuilder getQueryIdOrBuilder() {
      if (queryIdBuilder_ != null) {
        return queryIdBuilder_.getMessageOrBuilder();
      } else {
        return queryId_ == null ?
            vastdb.queryengine.protocol.QueryId.getDefaultInstance() : queryId_;
      }
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryId query_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.QueryId, vastdb.queryengine.protocol.QueryId.Builder, vastdb.queryengine.protocol.QueryIdOrBuilder> 
        getQueryIdFieldBuilder() {
      if (queryIdBuilder_ == null) {
        queryIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vastdb.queryengine.protocol.QueryId, vastdb.queryengine.protocol.QueryId.Builder, vastdb.queryengine.protocol.QueryIdOrBuilder>(
                getQueryId(),
                getParentForChildren(),
                isClean());
        queryId_ = null;
      }
      return queryIdBuilder_;
    }

    private com.google.protobuf.Timestamp startTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     * @return Whether the startTime field is set.
     */
    public boolean hasStartTime() {
      return startTimeBuilder_ != null || startTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     * @return The startTime.
     */
    public com.google.protobuf.Timestamp getStartTime() {
      if (startTimeBuilder_ == null) {
        return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
      } else {
        return startTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    public Builder setStartTime(com.google.protobuf.Timestamp value) {
      if (startTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startTime_ = value;
        onChanged();
      } else {
        startTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    public Builder setStartTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startTimeBuilder_ == null) {
        startTime_ = builderForValue.build();
        onChanged();
      } else {
        startTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    public Builder mergeStartTime(com.google.protobuf.Timestamp value) {
      if (startTimeBuilder_ == null) {
        if (startTime_ != null) {
          startTime_ =
            com.google.protobuf.Timestamp.newBuilder(startTime_).mergeFrom(value).buildPartial();
        } else {
          startTime_ = value;
        }
        onChanged();
      } else {
        startTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    public Builder clearStartTime() {
      if (startTimeBuilder_ == null) {
        startTime_ = null;
        onChanged();
      } else {
        startTime_ = null;
        startTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartTimeBuilder() {
      
      onChanged();
      return getStartTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder() {
      if (startTimeBuilder_ != null) {
        return startTimeBuilder_.getMessageOrBuilder();
      } else {
        return startTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartTimeFieldBuilder() {
      if (startTimeBuilder_ == null) {
        startTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStartTime(),
                getParentForChildren(),
                isClean());
        startTime_ = null;
      }
      return startTimeBuilder_;
    }

    private java.util.List<vastdb.queryengine.protocol.Metric> metrics_ =
      java.util.Collections.emptyList();
    private void ensureMetricsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        metrics_ = new java.util.ArrayList<vastdb.queryengine.protocol.Metric>(metrics_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        vastdb.queryengine.protocol.Metric, vastdb.queryengine.protocol.Metric.Builder, vastdb.queryengine.protocol.MetricOrBuilder> metricsBuilder_;

    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public java.util.List<vastdb.queryengine.protocol.Metric> getMetricsList() {
      if (metricsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metrics_);
      } else {
        return metricsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public int getMetricsCount() {
      if (metricsBuilder_ == null) {
        return metrics_.size();
      } else {
        return metricsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public vastdb.queryengine.protocol.Metric getMetrics(int index) {
      if (metricsBuilder_ == null) {
        return metrics_.get(index);
      } else {
        return metricsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder setMetrics(
        int index, vastdb.queryengine.protocol.Metric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.set(index, value);
        onChanged();
      } else {
        metricsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder setMetrics(
        int index, vastdb.queryengine.protocol.Metric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.set(index, builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder addMetrics(vastdb.queryengine.protocol.Metric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.add(value);
        onChanged();
      } else {
        metricsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder addMetrics(
        int index, vastdb.queryengine.protocol.Metric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.add(index, value);
        onChanged();
      } else {
        metricsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder addMetrics(
        vastdb.queryengine.protocol.Metric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.add(builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder addMetrics(
        int index, vastdb.queryengine.protocol.Metric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.add(index, builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder addAllMetrics(
        java.lang.Iterable<? extends vastdb.queryengine.protocol.Metric> values) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metrics_);
        onChanged();
      } else {
        metricsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder clearMetrics() {
      if (metricsBuilder_ == null) {
        metrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        metricsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public Builder removeMetrics(int index) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.remove(index);
        onChanged();
      } else {
        metricsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public vastdb.queryengine.protocol.Metric.Builder getMetricsBuilder(
        int index) {
      return getMetricsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public vastdb.queryengine.protocol.MetricOrBuilder getMetricsOrBuilder(
        int index) {
      if (metricsBuilder_ == null) {
        return metrics_.get(index);  } else {
        return metricsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public java.util.List<? extends vastdb.queryengine.protocol.MetricOrBuilder> 
         getMetricsOrBuilderList() {
      if (metricsBuilder_ != null) {
        return metricsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metrics_);
      }
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public vastdb.queryengine.protocol.Metric.Builder addMetricsBuilder() {
      return getMetricsFieldBuilder().addBuilder(
          vastdb.queryengine.protocol.Metric.getDefaultInstance());
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public vastdb.queryengine.protocol.Metric.Builder addMetricsBuilder(
        int index) {
      return getMetricsFieldBuilder().addBuilder(
          index, vastdb.queryengine.protocol.Metric.getDefaultInstance());
    }
    /**
     * <pre>
     * updated during query execution
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Metric metrics = 3;</code>
     */
    public java.util.List<vastdb.queryengine.protocol.Metric.Builder> 
         getMetricsBuilderList() {
      return getMetricsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        vastdb.queryengine.protocol.Metric, vastdb.queryengine.protocol.Metric.Builder, vastdb.queryengine.protocol.MetricOrBuilder> 
        getMetricsFieldBuilder() {
      if (metricsBuilder_ == null) {
        metricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            vastdb.queryengine.protocol.Metric, vastdb.queryengine.protocol.Metric.Builder, vastdb.queryengine.protocol.MetricOrBuilder>(
                metrics_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        metrics_ = null;
      }
      return metricsBuilder_;
    }

    private java.util.List<vastdb.queryengine.protocol.Ticket> tickets_ =
      java.util.Collections.emptyList();
    private void ensureTicketsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        tickets_ = new java.util.ArrayList<vastdb.queryengine.protocol.Ticket>(tickets_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        vastdb.queryengine.protocol.Ticket, vastdb.queryengine.protocol.Ticket.Builder, vastdb.queryengine.protocol.TicketOrBuilder> ticketsBuilder_;

    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public java.util.List<vastdb.queryengine.protocol.Ticket> getTicketsList() {
      if (ticketsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tickets_);
      } else {
        return ticketsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public int getTicketsCount() {
      if (ticketsBuilder_ == null) {
        return tickets_.size();
      } else {
        return ticketsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public vastdb.queryengine.protocol.Ticket getTickets(int index) {
      if (ticketsBuilder_ == null) {
        return tickets_.get(index);
      } else {
        return ticketsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder setTickets(
        int index, vastdb.queryengine.protocol.Ticket value) {
      if (ticketsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTicketsIsMutable();
        tickets_.set(index, value);
        onChanged();
      } else {
        ticketsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder setTickets(
        int index, vastdb.queryengine.protocol.Ticket.Builder builderForValue) {
      if (ticketsBuilder_ == null) {
        ensureTicketsIsMutable();
        tickets_.set(index, builderForValue.build());
        onChanged();
      } else {
        ticketsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder addTickets(vastdb.queryengine.protocol.Ticket value) {
      if (ticketsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTicketsIsMutable();
        tickets_.add(value);
        onChanged();
      } else {
        ticketsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder addTickets(
        int index, vastdb.queryengine.protocol.Ticket value) {
      if (ticketsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTicketsIsMutable();
        tickets_.add(index, value);
        onChanged();
      } else {
        ticketsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder addTickets(
        vastdb.queryengine.protocol.Ticket.Builder builderForValue) {
      if (ticketsBuilder_ == null) {
        ensureTicketsIsMutable();
        tickets_.add(builderForValue.build());
        onChanged();
      } else {
        ticketsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder addTickets(
        int index, vastdb.queryengine.protocol.Ticket.Builder builderForValue) {
      if (ticketsBuilder_ == null) {
        ensureTicketsIsMutable();
        tickets_.add(index, builderForValue.build());
        onChanged();
      } else {
        ticketsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder addAllTickets(
        java.lang.Iterable<? extends vastdb.queryengine.protocol.Ticket> values) {
      if (ticketsBuilder_ == null) {
        ensureTicketsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tickets_);
        onChanged();
      } else {
        ticketsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder clearTickets() {
      if (ticketsBuilder_ == null) {
        tickets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        ticketsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public Builder removeTickets(int index) {
      if (ticketsBuilder_ == null) {
        ensureTicketsIsMutable();
        tickets_.remove(index);
        onChanged();
      } else {
        ticketsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public vastdb.queryengine.protocol.Ticket.Builder getTicketsBuilder(
        int index) {
      return getTicketsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public vastdb.queryengine.protocol.TicketOrBuilder getTicketsOrBuilder(
        int index) {
      if (ticketsBuilder_ == null) {
        return tickets_.get(index);  } else {
        return ticketsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public java.util.List<? extends vastdb.queryengine.protocol.TicketOrBuilder> 
         getTicketsOrBuilderList() {
      if (ticketsBuilder_ != null) {
        return ticketsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tickets_);
      }
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public vastdb.queryengine.protocol.Ticket.Builder addTicketsBuilder() {
      return getTicketsFieldBuilder().addBuilder(
          vastdb.queryengine.protocol.Ticket.getDefaultInstance());
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public vastdb.queryengine.protocol.Ticket.Builder addTicketsBuilder(
        int index) {
      return getTicketsFieldBuilder().addBuilder(
          index, vastdb.queryengine.protocol.Ticket.getDefaultInstance());
    }
    /**
     * <pre>
     * # of tickets must not change between responses
     * </pre>
     *
     * <code>repeated .vastdb.queryengine.protocol.Ticket tickets = 4;</code>
     */
    public java.util.List<vastdb.queryengine.protocol.Ticket.Builder> 
         getTicketsBuilderList() {
      return getTicketsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        vastdb.queryengine.protocol.Ticket, vastdb.queryengine.protocol.Ticket.Builder, vastdb.queryengine.protocol.TicketOrBuilder> 
        getTicketsFieldBuilder() {
      if (ticketsBuilder_ == null) {
        ticketsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            vastdb.queryengine.protocol.Ticket, vastdb.queryengine.protocol.Ticket.Builder, vastdb.queryengine.protocol.TicketOrBuilder>(
                tickets_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        tickets_ = null;
      }
      return ticketsBuilder_;
    }

    private int statusCode_ ;
    /**
     * <code>optional uint32 status_code = 5;</code>
     * @return Whether the statusCode field is set.
     */
    @java.lang.Override
    public boolean hasStatusCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 status_code = 5;</code>
     * @return The statusCode.
     */
    @java.lang.Override
    public int getStatusCode() {
      return statusCode_;
    }
    /**
     * <code>optional uint32 status_code = 5;</code>
     * @param value The statusCode to set.
     * @return This builder for chaining.
     */
    public Builder setStatusCode(int value) {
      bitField0_ |= 0x00000004;
      statusCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 status_code = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusCode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      statusCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>optional string description = 6;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string description = 6;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string description = 6;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 6;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000008);
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 6;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      description_ = value;
      onChanged();
      return this;
    }

    private int state_ ;
    /**
     * <code>optional uint32 state = 7;</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override
    public boolean hasState() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 state = 7;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return state_;
    }
    /**
     * <code>optional uint32 state = 7;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(int value) {
      bitField0_ |= 0x00000010;
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 state = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000010);
      state_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vastdb.queryengine.protocol.QueryStatus)
  }

  // @@protoc_insertion_point(class_scope:vastdb.queryengine.protocol.QueryStatus)
  private static final vastdb.queryengine.protocol.QueryStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vastdb.queryengine.protocol.QueryStatus();
  }

  public static vastdb.queryengine.protocol.QueryStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryStatus>
      PARSER = new com.google.protobuf.AbstractParser<QueryStatus>() {
    @java.lang.Override
    public QueryStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QueryStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vastdb.queryengine.protocol.QueryStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

