// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface QueryEngineGetCapabilitiesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.QueryEngineGetCapabilitiesRequest)
    com.google.protobuf.MessageOrBuilder {
}
