// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface SessionOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.SessionOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string string_value = 2;</code>
   * @return Whether the stringValue field is set.
   */
  boolean hasStringValue();
  /**
   * <code>string string_value = 2;</code>
   * @return The stringValue.
   */
  java.lang.String getStringValue();
  /**
   * <code>string string_value = 2;</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>bool bool_value = 3;</code>
   * @return Whether the boolValue field is set.
   */
  boolean hasBoolValue();
  /**
   * <code>bool bool_value = 3;</code>
   * @return The boolValue.
   */
  boolean getBoolValue();

  /**
   * <code>sfixed64 int64_value = 4;</code>
   * @return Whether the int64Value field is set.
   */
  boolean hasInt64Value();
  /**
   * <code>sfixed64 int64_value = 4;</code>
   * @return The int64Value.
   */
  long getInt64Value();

  /**
   * <code>double double_value = 5;</code>
   * @return Whether the doubleValue field is set.
   */
  boolean hasDoubleValue();
  /**
   * <code>double double_value = 5;</code>
   * @return The doubleValue.
   */
  double getDoubleValue();

  /**
   * <code>bytes bytes_value = 6;</code>
   * @return Whether the bytesValue field is set.
   */
  boolean hasBytesValue();
  /**
   * <code>bytes bytes_value = 6;</code>
   * @return The bytesValue.
   */
  com.google.protobuf.ByteString getBytesValue();

  /**
   * <code>.vastdb.queryengine.protocol.SessionOptionScope scope = 7;</code>
   * @return The enum numeric value on the wire for scope.
   */
  int getScopeValue();
  /**
   * <code>.vastdb.queryengine.protocol.SessionOptionScope scope = 7;</code>
   * @return The scope.
   */
  vastdb.queryengine.protocol.SessionOptionScope getScope();

  public vastdb.queryengine.protocol.SessionOption.ValueCase getValueCase();
}
