// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

/**
 * Protobuf enum {@code vastdb.queryengine.protocol.SessionOptionScope}
 */
public enum SessionOptionScope
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>USER_VARIABLE = 0;</code>
   */
  USER_VARIABLE(0),
  /**
   * <pre>
   * GLOBAL = 2;  // Not implemented yet
   * LOCAL = 3;  // Not implemented in DuckDB as of 1.4
   * </pre>
   *
   * <code>SESSION = 1;</code>
   */
  SESSION(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>USER_VARIABLE = 0;</code>
   */
  public static final int USER_VARIABLE_VALUE = 0;
  /**
   * <pre>
   * GLOBAL = 2;  // Not implemented yet
   * LOCAL = 3;  // Not implemented in DuckDB as of 1.4
   * </pre>
   *
   * <code>SESSION = 1;</code>
   */
  public static final int SESSION_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SessionOptionScope valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SessionOptionScope forNumber(int value) {
    switch (value) {
      case 0: return USER_VARIABLE;
      case 1: return SESSION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SessionOptionScope>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SessionOptionScope> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SessionOptionScope>() {
          public SessionOptionScope findValueByNumber(int number) {
            return SessionOptionScope.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return vastdb.queryengine.protocol.Vastdb.getDescriptor().getEnumTypes().get(0);
  }

  private static final SessionOptionScope[] VALUES = values();

  public static SessionOptionScope valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SessionOptionScope(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:vastdb.queryengine.protocol.SessionOptionScope)
}

