// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

/**
 * <pre>
 * coordinator-&gt;client
 * two valid and mutually exclusive configurations for this message
 * 1. when message is sent in the start of HTTP body, with its size specified by the
 *    tabular-protobuf-size HTTP header. This message will be followed (concatenated) by a stream
 *    of serialized Arrow `RecordBatch` objects, using the
 *    https://arrow.apache.org/docs/format/Columnar.html#encapsulated-message-format encoding.
 *    In this configuration `status.tickets` must be empty
 * 2. status.tickets is supplied
 * the first configuration will be used for EXPLAIN &amp; latency-critical queries (no pagination) 
 * </pre>
 *
 * Protobuf type {@code vastdb.queryengine.protocol.StartQueryResponse}
 */
public final class StartQueryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vastdb.queryengine.protocol.StartQueryResponse)
    StartQueryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StartQueryResponse.newBuilder() to construct.
  private StartQueryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StartQueryResponse() {
    arrowSchema_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StartQueryResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vastdb.queryengine.protocol.StartQueryResponse.class, vastdb.queryengine.protocol.StartQueryResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private vastdb.queryengine.protocol.QueryStatus status_;
  /**
   * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.QueryStatus getStatus() {
    return status_ == null ? vastdb.queryengine.protocol.QueryStatus.getDefaultInstance() : status_;
  }
  /**
   * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.QueryStatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int ARROW_SCHEMA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString arrowSchema_;
  /**
   * <pre>
   * serialized Arrow schema of the query output (for parsing the `RecordBatch` stream)
   * </pre>
   *
   * <code>bytes arrow_schema = 2;</code>
   * @return The arrowSchema.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getArrowSchema() {
    return arrowSchema_;
  }

  public static final int IS_BLOCKING_FIELD_NUMBER = 3;
  private boolean isBlocking_;
  /**
   * <pre>
   * tells the driver to block the client till the query is done
   * needed for deterministic handling of DDL, DML, TCL and DCL (Data {Definition, Manipulation, Control} Language, Transaction Control Language)
   * See Slack thread for more info: https://vastdata.slack.com/archives/C0825QQG005/p1764766025323339?thread_ts=1759916288.192959&amp;cid=C0825QQG005
   * </pre>
   *
   * <code>bool is_blocking = 3;</code>
   * @return The isBlocking.
   */
  @java.lang.Override
  public boolean getIsBlocking() {
    return isBlocking_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != null) {
      output.writeMessage(1, getStatus());
    }
    if (!arrowSchema_.isEmpty()) {
      output.writeBytes(2, arrowSchema_);
    }
    if (isBlocking_ != false) {
      output.writeBool(3, isBlocking_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (!arrowSchema_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, arrowSchema_);
    }
    if (isBlocking_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isBlocking_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vastdb.queryengine.protocol.StartQueryResponse)) {
      return super.equals(obj);
    }
    vastdb.queryengine.protocol.StartQueryResponse other = (vastdb.queryengine.protocol.StartQueryResponse) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!getArrowSchema()
        .equals(other.getArrowSchema())) return false;
    if (getIsBlocking()
        != other.getIsBlocking()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (37 * hash) + ARROW_SCHEMA_FIELD_NUMBER;
    hash = (53 * hash) + getArrowSchema().hashCode();
    hash = (37 * hash) + IS_BLOCKING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsBlocking());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.StartQueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vastdb.queryengine.protocol.StartQueryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * coordinator-&gt;client
   * two valid and mutually exclusive configurations for this message
   * 1. when message is sent in the start of HTTP body, with its size specified by the
   *    tabular-protobuf-size HTTP header. This message will be followed (concatenated) by a stream
   *    of serialized Arrow `RecordBatch` objects, using the
   *    https://arrow.apache.org/docs/format/Columnar.html#encapsulated-message-format encoding.
   *    In this configuration `status.tickets` must be empty
   * 2. status.tickets is supplied
   * the first configuration will be used for EXPLAIN &amp; latency-critical queries (no pagination) 
   * </pre>
   *
   * Protobuf type {@code vastdb.queryengine.protocol.StartQueryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vastdb.queryengine.protocol.StartQueryResponse)
      vastdb.queryengine.protocol.StartQueryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vastdb.queryengine.protocol.StartQueryResponse.class, vastdb.queryengine.protocol.StartQueryResponse.Builder.class);
    }

    // Construct using vastdb.queryengine.protocol.StartQueryResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      arrowSchema_ = com.google.protobuf.ByteString.EMPTY;

      isBlocking_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryResponse_descriptor;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.StartQueryResponse getDefaultInstanceForType() {
      return vastdb.queryengine.protocol.StartQueryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.StartQueryResponse build() {
      vastdb.queryengine.protocol.StartQueryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.StartQueryResponse buildPartial() {
      vastdb.queryengine.protocol.StartQueryResponse result = new vastdb.queryengine.protocol.StartQueryResponse(this);
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      result.arrowSchema_ = arrowSchema_;
      result.isBlocking_ = isBlocking_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vastdb.queryengine.protocol.StartQueryResponse) {
        return mergeFrom((vastdb.queryengine.protocol.StartQueryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vastdb.queryengine.protocol.StartQueryResponse other) {
      if (other == vastdb.queryengine.protocol.StartQueryResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.getArrowSchema() != com.google.protobuf.ByteString.EMPTY) {
        setArrowSchema(other.getArrowSchema());
      }
      if (other.getIsBlocking() != false) {
        setIsBlocking(other.getIsBlocking());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStatusFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              arrowSchema_ = input.readBytes();

              break;
            } // case 18
            case 24: {
              isBlocking_ = input.readBool();

              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private vastdb.queryengine.protocol.QueryStatus status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.QueryStatus, vastdb.queryengine.protocol.QueryStatus.Builder, vastdb.queryengine.protocol.QueryStatusOrBuilder> statusBuilder_;
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     * @return The status.
     */
    public vastdb.queryengine.protocol.QueryStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? vastdb.queryengine.protocol.QueryStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     */
    public Builder setStatus(vastdb.queryengine.protocol.QueryStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     */
    public Builder setStatus(
        vastdb.queryengine.protocol.QueryStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     */
    public Builder mergeStatus(vastdb.queryengine.protocol.QueryStatus value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            vastdb.queryengine.protocol.QueryStatus.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     */
    public vastdb.queryengine.protocol.QueryStatus.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     */
    public vastdb.queryengine.protocol.QueryStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            vastdb.queryengine.protocol.QueryStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.vastdb.queryengine.protocol.QueryStatus status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.QueryStatus, vastdb.queryengine.protocol.QueryStatus.Builder, vastdb.queryengine.protocol.QueryStatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vastdb.queryengine.protocol.QueryStatus, vastdb.queryengine.protocol.QueryStatus.Builder, vastdb.queryengine.protocol.QueryStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private com.google.protobuf.ByteString arrowSchema_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * serialized Arrow schema of the query output (for parsing the `RecordBatch` stream)
     * </pre>
     *
     * <code>bytes arrow_schema = 2;</code>
     * @return The arrowSchema.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getArrowSchema() {
      return arrowSchema_;
    }
    /**
     * <pre>
     * serialized Arrow schema of the query output (for parsing the `RecordBatch` stream)
     * </pre>
     *
     * <code>bytes arrow_schema = 2;</code>
     * @param value The arrowSchema to set.
     * @return This builder for chaining.
     */
    public Builder setArrowSchema(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arrowSchema_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * serialized Arrow schema of the query output (for parsing the `RecordBatch` stream)
     * </pre>
     *
     * <code>bytes arrow_schema = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearArrowSchema() {
      
      arrowSchema_ = getDefaultInstance().getArrowSchema();
      onChanged();
      return this;
    }

    private boolean isBlocking_ ;
    /**
     * <pre>
     * tells the driver to block the client till the query is done
     * needed for deterministic handling of DDL, DML, TCL and DCL (Data {Definition, Manipulation, Control} Language, Transaction Control Language)
     * See Slack thread for more info: https://vastdata.slack.com/archives/C0825QQG005/p1764766025323339?thread_ts=1759916288.192959&amp;cid=C0825QQG005
     * </pre>
     *
     * <code>bool is_blocking = 3;</code>
     * @return The isBlocking.
     */
    @java.lang.Override
    public boolean getIsBlocking() {
      return isBlocking_;
    }
    /**
     * <pre>
     * tells the driver to block the client till the query is done
     * needed for deterministic handling of DDL, DML, TCL and DCL (Data {Definition, Manipulation, Control} Language, Transaction Control Language)
     * See Slack thread for more info: https://vastdata.slack.com/archives/C0825QQG005/p1764766025323339?thread_ts=1759916288.192959&amp;cid=C0825QQG005
     * </pre>
     *
     * <code>bool is_blocking = 3;</code>
     * @param value The isBlocking to set.
     * @return This builder for chaining.
     */
    public Builder setIsBlocking(boolean value) {
      
      isBlocking_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tells the driver to block the client till the query is done
     * needed for deterministic handling of DDL, DML, TCL and DCL (Data {Definition, Manipulation, Control} Language, Transaction Control Language)
     * See Slack thread for more info: https://vastdata.slack.com/archives/C0825QQG005/p1764766025323339?thread_ts=1759916288.192959&amp;cid=C0825QQG005
     * </pre>
     *
     * <code>bool is_blocking = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsBlocking() {
      
      isBlocking_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vastdb.queryengine.protocol.StartQueryResponse)
  }

  // @@protoc_insertion_point(class_scope:vastdb.queryengine.protocol.StartQueryResponse)
  private static final vastdb.queryengine.protocol.StartQueryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vastdb.queryengine.protocol.StartQueryResponse();
  }

  public static vastdb.queryengine.protocol.StartQueryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StartQueryResponse>
      PARSER = new com.google.protobuf.AbstractParser<StartQueryResponse>() {
    @java.lang.Override
    public StartQueryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StartQueryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StartQueryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vastdb.queryengine.protocol.StartQueryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

