// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

/**
 * <pre>
 * client-&gt;coordinator: returns after the query is scheduled for execution
 * </pre>
 *
 * Protobuf type {@code vastdb.queryengine.protocol.StartQueryRequest}
 */
public final class StartQueryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vastdb.queryengine.protocol.StartQueryRequest)
    StartQueryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StartQueryRequest.newBuilder() to construct.
  private StartQueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StartQueryRequest() {
    session_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StartQueryRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vastdb.queryengine.protocol.StartQueryRequest.class, vastdb.queryengine.protocol.StartQueryRequest.Builder.class);
  }

  private int bitField0_;
  private int queryCase_ = 0;
  private java.lang.Object query_;
  public enum QueryCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SQL(3),
    SUBSTRAIT(4),
    COMPUTE_IR(5),
    QUERY_NOT_SET(0);
    private final int value;
    private QueryCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static QueryCase valueOf(int value) {
      return forNumber(value);
    }

    public static QueryCase forNumber(int value) {
      switch (value) {
        case 3: return SQL;
        case 4: return SUBSTRAIT;
        case 5: return COMPUTE_IR;
        case 0: return QUERY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public QueryCase
  getQueryCase() {
    return QueryCase.forNumber(
        queryCase_);
  }

  public static final int SESSION_FIELD_NUMBER = 1;
  private java.util.List<vastdb.queryengine.protocol.SessionOption> session_;
  /**
   * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
   */
  @java.lang.Override
  public java.util.List<vastdb.queryengine.protocol.SessionOption> getSessionList() {
    return session_;
  }
  /**
   * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends vastdb.queryengine.protocol.SessionOptionOrBuilder> 
      getSessionOrBuilderList() {
    return session_;
  }
  /**
   * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
   */
  @java.lang.Override
  public int getSessionCount() {
    return session_.size();
  }
  /**
   * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.SessionOption getSession(int index) {
    return session_.get(index);
  }
  /**
   * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.SessionOptionOrBuilder getSessionOrBuilder(
      int index) {
    return session_.get(index);
  }

  public static final int TXID_FIELD_NUMBER = 2;
  private long txid_;
  /**
   * <code>optional uint64 txid = 2;</code>
   * @return Whether the txid field is set.
   */
  @java.lang.Override
  public boolean hasTxid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 txid = 2;</code>
   * @return The txid.
   */
  @java.lang.Override
  public long getTxid() {
    return txid_;
  }

  public static final int SQL_FIELD_NUMBER = 3;
  /**
   * <code>string sql = 3;</code>
   * @return Whether the sql field is set.
   */
  public boolean hasSql() {
    return queryCase_ == 3;
  }
  /**
   * <code>string sql = 3;</code>
   * @return The sql.
   */
  public java.lang.String getSql() {
    java.lang.Object ref = "";
    if (queryCase_ == 3) {
      ref = query_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (queryCase_ == 3) {
        query_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string sql = 3;</code>
   * @return The bytes for sql.
   */
  public com.google.protobuf.ByteString
      getSqlBytes() {
    java.lang.Object ref = "";
    if (queryCase_ == 3) {
      ref = query_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (queryCase_ == 3) {
        query_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBSTRAIT_FIELD_NUMBER = 4;
  /**
   * <pre>
   * NOT TODAY
   * </pre>
   *
   * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
   * @return Whether the substrait field is set.
   */
  @java.lang.Override
  public boolean hasSubstrait() {
    return queryCase_ == 4;
  }
  /**
   * <pre>
   * NOT TODAY
   * </pre>
   *
   * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
   * @return The substrait.
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.SerializedPlan getSubstrait() {
    if (queryCase_ == 4) {
       return (vastdb.queryengine.protocol.SerializedPlan) query_;
    }
    return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
  }
  /**
   * <pre>
   * NOT TODAY
   * </pre>
   *
   * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.SerializedPlanOrBuilder getSubstraitOrBuilder() {
    if (queryCase_ == 4) {
       return (vastdb.queryengine.protocol.SerializedPlan) query_;
    }
    return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
  }

  public static final int COMPUTE_IR_FIELD_NUMBER = 5;
  /**
   * <pre>
   * for legacy `QueryData` flow
   * </pre>
   *
   * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
   * @return Whether the computeIr field is set.
   */
  @java.lang.Override
  public boolean hasComputeIr() {
    return queryCase_ == 5;
  }
  /**
   * <pre>
   * for legacy `QueryData` flow
   * </pre>
   *
   * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
   * @return The computeIr.
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.SerializedPlan getComputeIr() {
    if (queryCase_ == 5) {
       return (vastdb.queryengine.protocol.SerializedPlan) query_;
    }
    return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
  }
  /**
   * <pre>
   * for legacy `QueryData` flow
   * </pre>
   *
   * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
   */
  @java.lang.Override
  public vastdb.queryengine.protocol.SerializedPlanOrBuilder getComputeIrOrBuilder() {
    if (queryCase_ == 5) {
       return (vastdb.queryengine.protocol.SerializedPlan) query_;
    }
    return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
  }

  public static final int QUERY_TIMEOUT_SEC_FIELD_NUMBER = 6;
  private long queryTimeoutSec_;
  /**
   * <code>optional uint64 query_timeout_sec = 6;</code>
   * @return Whether the queryTimeoutSec field is set.
   */
  @java.lang.Override
  public boolean hasQueryTimeoutSec() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint64 query_timeout_sec = 6;</code>
   * @return The queryTimeoutSec.
   */
  @java.lang.Override
  public long getQueryTimeoutSec() {
    return queryTimeoutSec_;
  }

  public static final int MAX_ENDPOINTS_FIELD_NUMBER = 7;
  private int maxEndpoints_;
  /**
   * <pre>
   * Note: the endpoints returned must be accessible from the client
   * If zero, query result will be sent via `StartQueryResponse` (no need to `GetData`)
   * </pre>
   *
   * <code>uint32 max_endpoints = 7;</code>
   * @return The maxEndpoints.
   */
  @java.lang.Override
  public int getMaxEndpoints() {
    return maxEndpoints_;
  }

  public static final int SUPPORT_HA_FIELD_NUMBER = 8;
  private boolean supportHa_;
  /**
   * <code>bool support_ha = 8;</code>
   * @return The supportHa.
   */
  @java.lang.Override
  public boolean getSupportHa() {
    return supportHa_;
  }

  public static final int SPLITS_FIELD_NUMBER = 9;
  private int splits_;
  /**
   * <code>optional uint32 splits = 9;</code>
   * @return Whether the splits field is set.
   */
  @java.lang.Override
  public boolean hasSplits() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint32 splits = 9;</code>
   * @return The splits.
   */
  @java.lang.Override
  public int getSplits() {
    return splits_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < session_.size(); i++) {
      output.writeMessage(1, session_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(2, txid_);
    }
    if (queryCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, query_);
    }
    if (queryCase_ == 4) {
      output.writeMessage(4, (vastdb.queryengine.protocol.SerializedPlan) query_);
    }
    if (queryCase_ == 5) {
      output.writeMessage(5, (vastdb.queryengine.protocol.SerializedPlan) query_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt64(6, queryTimeoutSec_);
    }
    if (maxEndpoints_ != 0) {
      output.writeUInt32(7, maxEndpoints_);
    }
    if (supportHa_ != false) {
      output.writeBool(8, supportHa_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(9, splits_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < session_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, session_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, txid_);
    }
    if (queryCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, query_);
    }
    if (queryCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (vastdb.queryengine.protocol.SerializedPlan) query_);
    }
    if (queryCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (vastdb.queryengine.protocol.SerializedPlan) query_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, queryTimeoutSec_);
    }
    if (maxEndpoints_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, maxEndpoints_);
    }
    if (supportHa_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, supportHa_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, splits_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vastdb.queryengine.protocol.StartQueryRequest)) {
      return super.equals(obj);
    }
    vastdb.queryengine.protocol.StartQueryRequest other = (vastdb.queryengine.protocol.StartQueryRequest) obj;

    if (!getSessionList()
        .equals(other.getSessionList())) return false;
    if (hasTxid() != other.hasTxid()) return false;
    if (hasTxid()) {
      if (getTxid()
          != other.getTxid()) return false;
    }
    if (hasQueryTimeoutSec() != other.hasQueryTimeoutSec()) return false;
    if (hasQueryTimeoutSec()) {
      if (getQueryTimeoutSec()
          != other.getQueryTimeoutSec()) return false;
    }
    if (getMaxEndpoints()
        != other.getMaxEndpoints()) return false;
    if (getSupportHa()
        != other.getSupportHa()) return false;
    if (hasSplits() != other.hasSplits()) return false;
    if (hasSplits()) {
      if (getSplits()
          != other.getSplits()) return false;
    }
    if (!getQueryCase().equals(other.getQueryCase())) return false;
    switch (queryCase_) {
      case 3:
        if (!getSql()
            .equals(other.getSql())) return false;
        break;
      case 4:
        if (!getSubstrait()
            .equals(other.getSubstrait())) return false;
        break;
      case 5:
        if (!getComputeIr()
            .equals(other.getComputeIr())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSessionCount() > 0) {
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSessionList().hashCode();
    }
    if (hasTxid()) {
      hash = (37 * hash) + TXID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTxid());
    }
    if (hasQueryTimeoutSec()) {
      hash = (37 * hash) + QUERY_TIMEOUT_SEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getQueryTimeoutSec());
    }
    hash = (37 * hash) + MAX_ENDPOINTS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxEndpoints();
    hash = (37 * hash) + SUPPORT_HA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSupportHa());
    if (hasSplits()) {
      hash = (37 * hash) + SPLITS_FIELD_NUMBER;
      hash = (53 * hash) + getSplits();
    }
    switch (queryCase_) {
      case 3:
        hash = (37 * hash) + SQL_FIELD_NUMBER;
        hash = (53 * hash) + getSql().hashCode();
        break;
      case 4:
        hash = (37 * hash) + SUBSTRAIT_FIELD_NUMBER;
        hash = (53 * hash) + getSubstrait().hashCode();
        break;
      case 5:
        hash = (37 * hash) + COMPUTE_IR_FIELD_NUMBER;
        hash = (53 * hash) + getComputeIr().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.StartQueryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vastdb.queryengine.protocol.StartQueryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * client-&gt;coordinator: returns after the query is scheduled for execution
   * </pre>
   *
   * Protobuf type {@code vastdb.queryengine.protocol.StartQueryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vastdb.queryengine.protocol.StartQueryRequest)
      vastdb.queryengine.protocol.StartQueryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vastdb.queryengine.protocol.StartQueryRequest.class, vastdb.queryengine.protocol.StartQueryRequest.Builder.class);
    }

    // Construct using vastdb.queryengine.protocol.StartQueryRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sessionBuilder_ == null) {
        session_ = java.util.Collections.emptyList();
      } else {
        session_ = null;
        sessionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      txid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (substraitBuilder_ != null) {
        substraitBuilder_.clear();
      }
      if (computeIrBuilder_ != null) {
        computeIrBuilder_.clear();
      }
      queryTimeoutSec_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      maxEndpoints_ = 0;

      supportHa_ = false;

      splits_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      queryCase_ = 0;
      query_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_StartQueryRequest_descriptor;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.StartQueryRequest getDefaultInstanceForType() {
      return vastdb.queryengine.protocol.StartQueryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.StartQueryRequest build() {
      vastdb.queryengine.protocol.StartQueryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.StartQueryRequest buildPartial() {
      vastdb.queryengine.protocol.StartQueryRequest result = new vastdb.queryengine.protocol.StartQueryRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (sessionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          session_ = java.util.Collections.unmodifiableList(session_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.session_ = session_;
      } else {
        result.session_ = sessionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.txid_ = txid_;
        to_bitField0_ |= 0x00000001;
      }
      if (queryCase_ == 3) {
        result.query_ = query_;
      }
      if (queryCase_ == 4) {
        if (substraitBuilder_ == null) {
          result.query_ = query_;
        } else {
          result.query_ = substraitBuilder_.build();
        }
      }
      if (queryCase_ == 5) {
        if (computeIrBuilder_ == null) {
          result.query_ = query_;
        } else {
          result.query_ = computeIrBuilder_.build();
        }
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.queryTimeoutSec_ = queryTimeoutSec_;
        to_bitField0_ |= 0x00000002;
      }
      result.maxEndpoints_ = maxEndpoints_;
      result.supportHa_ = supportHa_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.splits_ = splits_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      result.queryCase_ = queryCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vastdb.queryengine.protocol.StartQueryRequest) {
        return mergeFrom((vastdb.queryengine.protocol.StartQueryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vastdb.queryengine.protocol.StartQueryRequest other) {
      if (other == vastdb.queryengine.protocol.StartQueryRequest.getDefaultInstance()) return this;
      if (sessionBuilder_ == null) {
        if (!other.session_.isEmpty()) {
          if (session_.isEmpty()) {
            session_ = other.session_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSessionIsMutable();
            session_.addAll(other.session_);
          }
          onChanged();
        }
      } else {
        if (!other.session_.isEmpty()) {
          if (sessionBuilder_.isEmpty()) {
            sessionBuilder_.dispose();
            sessionBuilder_ = null;
            session_ = other.session_;
            bitField0_ = (bitField0_ & ~0x00000001);
            sessionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSessionFieldBuilder() : null;
          } else {
            sessionBuilder_.addAllMessages(other.session_);
          }
        }
      }
      if (other.hasTxid()) {
        setTxid(other.getTxid());
      }
      if (other.hasQueryTimeoutSec()) {
        setQueryTimeoutSec(other.getQueryTimeoutSec());
      }
      if (other.getMaxEndpoints() != 0) {
        setMaxEndpoints(other.getMaxEndpoints());
      }
      if (other.getSupportHa() != false) {
        setSupportHa(other.getSupportHa());
      }
      if (other.hasSplits()) {
        setSplits(other.getSplits());
      }
      switch (other.getQueryCase()) {
        case SQL: {
          queryCase_ = 3;
          query_ = other.query_;
          onChanged();
          break;
        }
        case SUBSTRAIT: {
          mergeSubstrait(other.getSubstrait());
          break;
        }
        case COMPUTE_IR: {
          mergeComputeIr(other.getComputeIr());
          break;
        }
        case QUERY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              vastdb.queryengine.protocol.SessionOption m =
                  input.readMessage(
                      vastdb.queryengine.protocol.SessionOption.parser(),
                      extensionRegistry);
              if (sessionBuilder_ == null) {
                ensureSessionIsMutable();
                session_.add(m);
              } else {
                sessionBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              txid_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              queryCase_ = 3;
              query_ = s;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getSubstraitFieldBuilder().getBuilder(),
                  extensionRegistry);
              queryCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getComputeIrFieldBuilder().getBuilder(),
                  extensionRegistry);
              queryCase_ = 5;
              break;
            } // case 42
            case 48: {
              queryTimeoutSec_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 48
            case 56: {
              maxEndpoints_ = input.readUInt32();

              break;
            } // case 56
            case 64: {
              supportHa_ = input.readBool();

              break;
            } // case 64
            case 72: {
              splits_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int queryCase_ = 0;
    private java.lang.Object query_;
    public QueryCase
        getQueryCase() {
      return QueryCase.forNumber(
          queryCase_);
    }

    public Builder clearQuery() {
      queryCase_ = 0;
      query_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.util.List<vastdb.queryengine.protocol.SessionOption> session_ =
      java.util.Collections.emptyList();
    private void ensureSessionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        session_ = new java.util.ArrayList<vastdb.queryengine.protocol.SessionOption>(session_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        vastdb.queryengine.protocol.SessionOption, vastdb.queryengine.protocol.SessionOption.Builder, vastdb.queryengine.protocol.SessionOptionOrBuilder> sessionBuilder_;

    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public java.util.List<vastdb.queryengine.protocol.SessionOption> getSessionList() {
      if (sessionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(session_);
      } else {
        return sessionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public int getSessionCount() {
      if (sessionBuilder_ == null) {
        return session_.size();
      } else {
        return sessionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public vastdb.queryengine.protocol.SessionOption getSession(int index) {
      if (sessionBuilder_ == null) {
        return session_.get(index);
      } else {
        return sessionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder setSession(
        int index, vastdb.queryengine.protocol.SessionOption value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionIsMutable();
        session_.set(index, value);
        onChanged();
      } else {
        sessionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder setSession(
        int index, vastdb.queryengine.protocol.SessionOption.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        session_.set(index, builderForValue.build());
        onChanged();
      } else {
        sessionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder addSession(vastdb.queryengine.protocol.SessionOption value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionIsMutable();
        session_.add(value);
        onChanged();
      } else {
        sessionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder addSession(
        int index, vastdb.queryengine.protocol.SessionOption value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionIsMutable();
        session_.add(index, value);
        onChanged();
      } else {
        sessionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder addSession(
        vastdb.queryengine.protocol.SessionOption.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        session_.add(builderForValue.build());
        onChanged();
      } else {
        sessionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder addSession(
        int index, vastdb.queryengine.protocol.SessionOption.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        session_.add(index, builderForValue.build());
        onChanged();
      } else {
        sessionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder addAllSession(
        java.lang.Iterable<? extends vastdb.queryengine.protocol.SessionOption> values) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, session_);
        onChanged();
      } else {
        sessionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder clearSession() {
      if (sessionBuilder_ == null) {
        session_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        sessionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public Builder removeSession(int index) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        session_.remove(index);
        onChanged();
      } else {
        sessionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public vastdb.queryengine.protocol.SessionOption.Builder getSessionBuilder(
        int index) {
      return getSessionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public vastdb.queryengine.protocol.SessionOptionOrBuilder getSessionOrBuilder(
        int index) {
      if (sessionBuilder_ == null) {
        return session_.get(index);  } else {
        return sessionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public java.util.List<? extends vastdb.queryengine.protocol.SessionOptionOrBuilder> 
         getSessionOrBuilderList() {
      if (sessionBuilder_ != null) {
        return sessionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(session_);
      }
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public vastdb.queryengine.protocol.SessionOption.Builder addSessionBuilder() {
      return getSessionFieldBuilder().addBuilder(
          vastdb.queryengine.protocol.SessionOption.getDefaultInstance());
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public vastdb.queryengine.protocol.SessionOption.Builder addSessionBuilder(
        int index) {
      return getSessionFieldBuilder().addBuilder(
          index, vastdb.queryengine.protocol.SessionOption.getDefaultInstance());
    }
    /**
     * <code>repeated .vastdb.queryengine.protocol.SessionOption session = 1;</code>
     */
    public java.util.List<vastdb.queryengine.protocol.SessionOption.Builder> 
         getSessionBuilderList() {
      return getSessionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        vastdb.queryengine.protocol.SessionOption, vastdb.queryengine.protocol.SessionOption.Builder, vastdb.queryengine.protocol.SessionOptionOrBuilder> 
        getSessionFieldBuilder() {
      if (sessionBuilder_ == null) {
        sessionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            vastdb.queryengine.protocol.SessionOption, vastdb.queryengine.protocol.SessionOption.Builder, vastdb.queryengine.protocol.SessionOptionOrBuilder>(
                session_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        session_ = null;
      }
      return sessionBuilder_;
    }

    private long txid_ ;
    /**
     * <code>optional uint64 txid = 2;</code>
     * @return Whether the txid field is set.
     */
    @java.lang.Override
    public boolean hasTxid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 txid = 2;</code>
     * @return The txid.
     */
    @java.lang.Override
    public long getTxid() {
      return txid_;
    }
    /**
     * <code>optional uint64 txid = 2;</code>
     * @param value The txid to set.
     * @return This builder for chaining.
     */
    public Builder setTxid(long value) {
      bitField0_ |= 0x00000002;
      txid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 txid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTxid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      txid_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>string sql = 3;</code>
     * @return Whether the sql field is set.
     */
    @java.lang.Override
    public boolean hasSql() {
      return queryCase_ == 3;
    }
    /**
     * <code>string sql = 3;</code>
     * @return The sql.
     */
    @java.lang.Override
    public java.lang.String getSql() {
      java.lang.Object ref = "";
      if (queryCase_ == 3) {
        ref = query_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (queryCase_ == 3) {
          query_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sql = 3;</code>
     * @return The bytes for sql.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSqlBytes() {
      java.lang.Object ref = "";
      if (queryCase_ == 3) {
        ref = query_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (queryCase_ == 3) {
          query_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sql = 3;</code>
     * @param value The sql to set.
     * @return This builder for chaining.
     */
    public Builder setSql(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  queryCase_ = 3;
      query_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sql = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSql() {
      if (queryCase_ == 3) {
        queryCase_ = 0;
        query_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string sql = 3;</code>
     * @param value The bytes for sql to set.
     * @return This builder for chaining.
     */
    public Builder setSqlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      queryCase_ = 3;
      query_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.SerializedPlan, vastdb.queryengine.protocol.SerializedPlan.Builder, vastdb.queryengine.protocol.SerializedPlanOrBuilder> substraitBuilder_;
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     * @return Whether the substrait field is set.
     */
    @java.lang.Override
    public boolean hasSubstrait() {
      return queryCase_ == 4;
    }
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     * @return The substrait.
     */
    @java.lang.Override
    public vastdb.queryengine.protocol.SerializedPlan getSubstrait() {
      if (substraitBuilder_ == null) {
        if (queryCase_ == 4) {
          return (vastdb.queryengine.protocol.SerializedPlan) query_;
        }
        return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
      } else {
        if (queryCase_ == 4) {
          return substraitBuilder_.getMessage();
        }
        return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     */
    public Builder setSubstrait(vastdb.queryengine.protocol.SerializedPlan value) {
      if (substraitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        query_ = value;
        onChanged();
      } else {
        substraitBuilder_.setMessage(value);
      }
      queryCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     */
    public Builder setSubstrait(
        vastdb.queryengine.protocol.SerializedPlan.Builder builderForValue) {
      if (substraitBuilder_ == null) {
        query_ = builderForValue.build();
        onChanged();
      } else {
        substraitBuilder_.setMessage(builderForValue.build());
      }
      queryCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     */
    public Builder mergeSubstrait(vastdb.queryengine.protocol.SerializedPlan value) {
      if (substraitBuilder_ == null) {
        if (queryCase_ == 4 &&
            query_ != vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance()) {
          query_ = vastdb.queryengine.protocol.SerializedPlan.newBuilder((vastdb.queryengine.protocol.SerializedPlan) query_)
              .mergeFrom(value).buildPartial();
        } else {
          query_ = value;
        }
        onChanged();
      } else {
        if (queryCase_ == 4) {
          substraitBuilder_.mergeFrom(value);
        }
        substraitBuilder_.setMessage(value);
      }
      queryCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     */
    public Builder clearSubstrait() {
      if (substraitBuilder_ == null) {
        if (queryCase_ == 4) {
          queryCase_ = 0;
          query_ = null;
          onChanged();
        }
      } else {
        if (queryCase_ == 4) {
          queryCase_ = 0;
          query_ = null;
        }
        substraitBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     */
    public vastdb.queryengine.protocol.SerializedPlan.Builder getSubstraitBuilder() {
      return getSubstraitFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     */
    @java.lang.Override
    public vastdb.queryengine.protocol.SerializedPlanOrBuilder getSubstraitOrBuilder() {
      if ((queryCase_ == 4) && (substraitBuilder_ != null)) {
        return substraitBuilder_.getMessageOrBuilder();
      } else {
        if (queryCase_ == 4) {
          return (vastdb.queryengine.protocol.SerializedPlan) query_;
        }
        return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * NOT TODAY
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan substrait = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.SerializedPlan, vastdb.queryengine.protocol.SerializedPlan.Builder, vastdb.queryengine.protocol.SerializedPlanOrBuilder> 
        getSubstraitFieldBuilder() {
      if (substraitBuilder_ == null) {
        if (!(queryCase_ == 4)) {
          query_ = vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
        }
        substraitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vastdb.queryengine.protocol.SerializedPlan, vastdb.queryengine.protocol.SerializedPlan.Builder, vastdb.queryengine.protocol.SerializedPlanOrBuilder>(
                (vastdb.queryengine.protocol.SerializedPlan) query_,
                getParentForChildren(),
                isClean());
        query_ = null;
      }
      queryCase_ = 4;
      onChanged();;
      return substraitBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.SerializedPlan, vastdb.queryengine.protocol.SerializedPlan.Builder, vastdb.queryengine.protocol.SerializedPlanOrBuilder> computeIrBuilder_;
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     * @return Whether the computeIr field is set.
     */
    @java.lang.Override
    public boolean hasComputeIr() {
      return queryCase_ == 5;
    }
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     * @return The computeIr.
     */
    @java.lang.Override
    public vastdb.queryengine.protocol.SerializedPlan getComputeIr() {
      if (computeIrBuilder_ == null) {
        if (queryCase_ == 5) {
          return (vastdb.queryengine.protocol.SerializedPlan) query_;
        }
        return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
      } else {
        if (queryCase_ == 5) {
          return computeIrBuilder_.getMessage();
        }
        return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     */
    public Builder setComputeIr(vastdb.queryengine.protocol.SerializedPlan value) {
      if (computeIrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        query_ = value;
        onChanged();
      } else {
        computeIrBuilder_.setMessage(value);
      }
      queryCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     */
    public Builder setComputeIr(
        vastdb.queryengine.protocol.SerializedPlan.Builder builderForValue) {
      if (computeIrBuilder_ == null) {
        query_ = builderForValue.build();
        onChanged();
      } else {
        computeIrBuilder_.setMessage(builderForValue.build());
      }
      queryCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     */
    public Builder mergeComputeIr(vastdb.queryengine.protocol.SerializedPlan value) {
      if (computeIrBuilder_ == null) {
        if (queryCase_ == 5 &&
            query_ != vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance()) {
          query_ = vastdb.queryengine.protocol.SerializedPlan.newBuilder((vastdb.queryengine.protocol.SerializedPlan) query_)
              .mergeFrom(value).buildPartial();
        } else {
          query_ = value;
        }
        onChanged();
      } else {
        if (queryCase_ == 5) {
          computeIrBuilder_.mergeFrom(value);
        }
        computeIrBuilder_.setMessage(value);
      }
      queryCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     */
    public Builder clearComputeIr() {
      if (computeIrBuilder_ == null) {
        if (queryCase_ == 5) {
          queryCase_ = 0;
          query_ = null;
          onChanged();
        }
      } else {
        if (queryCase_ == 5) {
          queryCase_ = 0;
          query_ = null;
        }
        computeIrBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     */
    public vastdb.queryengine.protocol.SerializedPlan.Builder getComputeIrBuilder() {
      return getComputeIrFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     */
    @java.lang.Override
    public vastdb.queryengine.protocol.SerializedPlanOrBuilder getComputeIrOrBuilder() {
      if ((queryCase_ == 5) && (computeIrBuilder_ != null)) {
        return computeIrBuilder_.getMessageOrBuilder();
      } else {
        if (queryCase_ == 5) {
          return (vastdb.queryengine.protocol.SerializedPlan) query_;
        }
        return vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * for legacy `QueryData` flow
     * </pre>
     *
     * <code>.vastdb.queryengine.protocol.SerializedPlan compute_ir = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vastdb.queryengine.protocol.SerializedPlan, vastdb.queryengine.protocol.SerializedPlan.Builder, vastdb.queryengine.protocol.SerializedPlanOrBuilder> 
        getComputeIrFieldBuilder() {
      if (computeIrBuilder_ == null) {
        if (!(queryCase_ == 5)) {
          query_ = vastdb.queryengine.protocol.SerializedPlan.getDefaultInstance();
        }
        computeIrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vastdb.queryengine.protocol.SerializedPlan, vastdb.queryengine.protocol.SerializedPlan.Builder, vastdb.queryengine.protocol.SerializedPlanOrBuilder>(
                (vastdb.queryengine.protocol.SerializedPlan) query_,
                getParentForChildren(),
                isClean());
        query_ = null;
      }
      queryCase_ = 5;
      onChanged();;
      return computeIrBuilder_;
    }

    private long queryTimeoutSec_ ;
    /**
     * <code>optional uint64 query_timeout_sec = 6;</code>
     * @return Whether the queryTimeoutSec field is set.
     */
    @java.lang.Override
    public boolean hasQueryTimeoutSec() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 query_timeout_sec = 6;</code>
     * @return The queryTimeoutSec.
     */
    @java.lang.Override
    public long getQueryTimeoutSec() {
      return queryTimeoutSec_;
    }
    /**
     * <code>optional uint64 query_timeout_sec = 6;</code>
     * @param value The queryTimeoutSec to set.
     * @return This builder for chaining.
     */
    public Builder setQueryTimeoutSec(long value) {
      bitField0_ |= 0x00000004;
      queryTimeoutSec_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 query_timeout_sec = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryTimeoutSec() {
      bitField0_ = (bitField0_ & ~0x00000004);
      queryTimeoutSec_ = 0L;
      onChanged();
      return this;
    }

    private int maxEndpoints_ ;
    /**
     * <pre>
     * Note: the endpoints returned must be accessible from the client
     * If zero, query result will be sent via `StartQueryResponse` (no need to `GetData`)
     * </pre>
     *
     * <code>uint32 max_endpoints = 7;</code>
     * @return The maxEndpoints.
     */
    @java.lang.Override
    public int getMaxEndpoints() {
      return maxEndpoints_;
    }
    /**
     * <pre>
     * Note: the endpoints returned must be accessible from the client
     * If zero, query result will be sent via `StartQueryResponse` (no need to `GetData`)
     * </pre>
     *
     * <code>uint32 max_endpoints = 7;</code>
     * @param value The maxEndpoints to set.
     * @return This builder for chaining.
     */
    public Builder setMaxEndpoints(int value) {
      
      maxEndpoints_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Note: the endpoints returned must be accessible from the client
     * If zero, query result will be sent via `StartQueryResponse` (no need to `GetData`)
     * </pre>
     *
     * <code>uint32 max_endpoints = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxEndpoints() {
      
      maxEndpoints_ = 0;
      onChanged();
      return this;
    }

    private boolean supportHa_ ;
    /**
     * <code>bool support_ha = 8;</code>
     * @return The supportHa.
     */
    @java.lang.Override
    public boolean getSupportHa() {
      return supportHa_;
    }
    /**
     * <code>bool support_ha = 8;</code>
     * @param value The supportHa to set.
     * @return This builder for chaining.
     */
    public Builder setSupportHa(boolean value) {
      
      supportHa_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool support_ha = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSupportHa() {
      
      supportHa_ = false;
      onChanged();
      return this;
    }

    private int splits_ ;
    /**
     * <code>optional uint32 splits = 9;</code>
     * @return Whether the splits field is set.
     */
    @java.lang.Override
    public boolean hasSplits() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 splits = 9;</code>
     * @return The splits.
     */
    @java.lang.Override
    public int getSplits() {
      return splits_;
    }
    /**
     * <code>optional uint32 splits = 9;</code>
     * @param value The splits to set.
     * @return This builder for chaining.
     */
    public Builder setSplits(int value) {
      bitField0_ |= 0x00000008;
      splits_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 splits = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSplits() {
      bitField0_ = (bitField0_ & ~0x00000008);
      splits_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vastdb.queryengine.protocol.StartQueryRequest)
  }

  // @@protoc_insertion_point(class_scope:vastdb.queryengine.protocol.StartQueryRequest)
  private static final vastdb.queryengine.protocol.StartQueryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vastdb.queryengine.protocol.StartQueryRequest();
  }

  public static vastdb.queryengine.protocol.StartQueryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StartQueryRequest>
      PARSER = new com.google.protobuf.AbstractParser<StartQueryRequest>() {
    @java.lang.Override
    public StartQueryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StartQueryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StartQueryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vastdb.queryengine.protocol.StartQueryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

