// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface TicketIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.TicketId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * This message should not be used by the driver - it is used by the server side only, and by the client will be
   * supplied as google.protobuf.Any (will allow us to change the ticket id only from server side without making
   * client side changes)
   * </pre>
   *
   * <code>uint32 pipeline_id = 1;</code>
   * @return The pipelineId.
   */
  int getPipelineId();

  /**
   * <code>uint32 split_id = 2;</code>
   * @return The splitId.
   */
  int getSplitId();
}
