// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public interface TicketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vastdb.queryengine.protocol.Ticket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * where we can fetch the data from
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Endpoint endpoints = 2;</code>
   */
  java.util.List<vastdb.queryengine.protocol.Endpoint> 
      getEndpointsList();
  /**
   * <pre>
   * where we can fetch the data from
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Endpoint endpoints = 2;</code>
   */
  vastdb.queryengine.protocol.Endpoint getEndpoints(int index);
  /**
   * <pre>
   * where we can fetch the data from
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Endpoint endpoints = 2;</code>
   */
  int getEndpointsCount();
  /**
   * <pre>
   * where we can fetch the data from
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Endpoint endpoints = 2;</code>
   */
  java.util.List<? extends vastdb.queryengine.protocol.EndpointOrBuilder> 
      getEndpointsOrBuilderList();
  /**
   * <pre>
   * where we can fetch the data from
   * </pre>
   *
   * <code>repeated .vastdb.queryengine.protocol.Endpoint endpoints = 2;</code>
   */
  vastdb.queryengine.protocol.EndpointOrBuilder getEndpointsOrBuilder(
      int index);

  /**
   * <pre>
   * currently we will use 1 endpoint (to open a single Tabular RPC connection)
   * later we can use multiple endpoints (to fetch N Parquet files)
   * </pre>
   *
   * <code>.google.protobuf.Any ticket_id = 4;</code>
   * @return Whether the ticketId field is set.
   */
  boolean hasTicketId();
  /**
   * <pre>
   * currently we will use 1 endpoint (to open a single Tabular RPC connection)
   * later we can use multiple endpoints (to fetch N Parquet files)
   * </pre>
   *
   * <code>.google.protobuf.Any ticket_id = 4;</code>
   * @return The ticketId.
   */
  com.google.protobuf.Any getTicketId();
  /**
   * <pre>
   * currently we will use 1 endpoint (to open a single Tabular RPC connection)
   * later we can use multiple endpoints (to fetch N Parquet files)
   * </pre>
   *
   * <code>.google.protobuf.Any ticket_id = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getTicketIdOrBuilder();
}
