// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

/**
 * Protobuf type {@code vastdb.queryengine.protocol.TicketId}
 */
public final class TicketId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vastdb.queryengine.protocol.TicketId)
    TicketIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TicketId.newBuilder() to construct.
  private TicketId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TicketId() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TicketId();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_TicketId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_TicketId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vastdb.queryengine.protocol.TicketId.class, vastdb.queryengine.protocol.TicketId.Builder.class);
  }

  public static final int PIPELINE_ID_FIELD_NUMBER = 1;
  private int pipelineId_;
  /**
   * <pre>
   * This message should not be used by the driver - it is used by the server side only, and by the client will be
   * supplied as google.protobuf.Any (will allow us to change the ticket id only from server side without making
   * client side changes)
   * </pre>
   *
   * <code>uint32 pipeline_id = 1;</code>
   * @return The pipelineId.
   */
  @java.lang.Override
  public int getPipelineId() {
    return pipelineId_;
  }

  public static final int SPLIT_ID_FIELD_NUMBER = 2;
  private int splitId_;
  /**
   * <code>uint32 split_id = 2;</code>
   * @return The splitId.
   */
  @java.lang.Override
  public int getSplitId() {
    return splitId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pipelineId_ != 0) {
      output.writeUInt32(1, pipelineId_);
    }
    if (splitId_ != 0) {
      output.writeUInt32(2, splitId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pipelineId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, pipelineId_);
    }
    if (splitId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, splitId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vastdb.queryengine.protocol.TicketId)) {
      return super.equals(obj);
    }
    vastdb.queryengine.protocol.TicketId other = (vastdb.queryengine.protocol.TicketId) obj;

    if (getPipelineId()
        != other.getPipelineId()) return false;
    if (getSplitId()
        != other.getSplitId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PIPELINE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPipelineId();
    hash = (37 * hash) + SPLIT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSplitId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vastdb.queryengine.protocol.TicketId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.TicketId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.TicketId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vastdb.queryengine.protocol.TicketId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vastdb.queryengine.protocol.TicketId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vastdb.queryengine.protocol.TicketId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vastdb.queryengine.protocol.TicketId)
      vastdb.queryengine.protocol.TicketIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_TicketId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_TicketId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vastdb.queryengine.protocol.TicketId.class, vastdb.queryengine.protocol.TicketId.Builder.class);
    }

    // Construct using vastdb.queryengine.protocol.TicketId.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pipelineId_ = 0;

      splitId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vastdb.queryengine.protocol.Vastdb.internal_static_vastdb_queryengine_protocol_TicketId_descriptor;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.TicketId getDefaultInstanceForType() {
      return vastdb.queryengine.protocol.TicketId.getDefaultInstance();
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.TicketId build() {
      vastdb.queryengine.protocol.TicketId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vastdb.queryengine.protocol.TicketId buildPartial() {
      vastdb.queryengine.protocol.TicketId result = new vastdb.queryengine.protocol.TicketId(this);
      result.pipelineId_ = pipelineId_;
      result.splitId_ = splitId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vastdb.queryengine.protocol.TicketId) {
        return mergeFrom((vastdb.queryengine.protocol.TicketId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vastdb.queryengine.protocol.TicketId other) {
      if (other == vastdb.queryengine.protocol.TicketId.getDefaultInstance()) return this;
      if (other.getPipelineId() != 0) {
        setPipelineId(other.getPipelineId());
      }
      if (other.getSplitId() != 0) {
        setSplitId(other.getSplitId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              pipelineId_ = input.readUInt32();

              break;
            } // case 8
            case 16: {
              splitId_ = input.readUInt32();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int pipelineId_ ;
    /**
     * <pre>
     * This message should not be used by the driver - it is used by the server side only, and by the client will be
     * supplied as google.protobuf.Any (will allow us to change the ticket id only from server side without making
     * client side changes)
     * </pre>
     *
     * <code>uint32 pipeline_id = 1;</code>
     * @return The pipelineId.
     */
    @java.lang.Override
    public int getPipelineId() {
      return pipelineId_;
    }
    /**
     * <pre>
     * This message should not be used by the driver - it is used by the server side only, and by the client will be
     * supplied as google.protobuf.Any (will allow us to change the ticket id only from server side without making
     * client side changes)
     * </pre>
     *
     * <code>uint32 pipeline_id = 1;</code>
     * @param value The pipelineId to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineId(int value) {
      
      pipelineId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This message should not be used by the driver - it is used by the server side only, and by the client will be
     * supplied as google.protobuf.Any (will allow us to change the ticket id only from server side without making
     * client side changes)
     * </pre>
     *
     * <code>uint32 pipeline_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPipelineId() {
      
      pipelineId_ = 0;
      onChanged();
      return this;
    }

    private int splitId_ ;
    /**
     * <code>uint32 split_id = 2;</code>
     * @return The splitId.
     */
    @java.lang.Override
    public int getSplitId() {
      return splitId_;
    }
    /**
     * <code>uint32 split_id = 2;</code>
     * @param value The splitId to set.
     * @return This builder for chaining.
     */
    public Builder setSplitId(int value) {
      
      splitId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 split_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSplitId() {
      
      splitId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vastdb.queryengine.protocol.TicketId)
  }

  // @@protoc_insertion_point(class_scope:vastdb.queryengine.protocol.TicketId)
  private static final vastdb.queryengine.protocol.TicketId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vastdb.queryengine.protocol.TicketId();
  }

  public static vastdb.queryengine.protocol.TicketId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TicketId>
      PARSER = new com.google.protobuf.AbstractParser<TicketId>() {
    @java.lang.Override
    public TicketId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TicketId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TicketId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vastdb.queryengine.protocol.TicketId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

