// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vastdb.proto

package vastdb.queryengine.protocol;

public final class Vastdb {
  private Vastdb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_StartQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_StartQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_QueryId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_QueryId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_GetQueryStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_GetQueryStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_FinishQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_FinishQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_QueryStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_QueryStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_TicketId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_TicketId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_Ticket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_Ticket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_StartQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_StartQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_GetQueryStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_GetQueryStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_ListQueriesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_ListQueriesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_ListQueriesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_ListQueriesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_Offset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_Offset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_GetDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_GetDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_GetDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_GetDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_FinishDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_FinishDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_Cancellation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_Cancellation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_Namespace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_Namespace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_SessionOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_SessionOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_SerializedPlan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_SerializedPlan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_Metric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_Metric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vastdb_queryengine_protocol_Endpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vastdb_queryengine_protocol_Endpoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014vastdb.proto\022\033vastdb.queryengine.proto" +
      "col\032\037google/protobuf/timestamp.proto\032\031go" +
      "ogle/protobuf/any.proto\"#\n!QueryEngineGe" +
      "tCapabilitiesRequest\"]\n\"QueryEngineGetCa" +
      "pabilitiesResponse\022\026\n\016server_version\030\001 \001" +
      "(\t\022\037\n\027session_options_support\030\002 \001(\010\"\212\003\n\021" +
      "StartQueryRequest\022;\n\007session\030\001 \003(\0132*.vas" +
      "tdb.queryengine.protocol.SessionOption\022\021" +
      "\n\004txid\030\002 \001(\004H\001\210\001\001\022\r\n\003sql\030\003 \001(\tH\000\022@\n\tsubs" +
      "trait\030\004 \001(\0132+.vastdb.queryengine.protoco" +
      "l.SerializedPlanH\000\022A\n\ncompute_ir\030\005 \001(\0132+" +
      ".vastdb.queryengine.protocol.SerializedP" +
      "lanH\000\022\036\n\021query_timeout_sec\030\006 \001(\004H\002\210\001\001\022\025\n" +
      "\rmax_endpoints\030\007 \001(\r\022\022\n\nsupport_ha\030\010 \001(\010" +
      "\022\023\n\006splits\030\t \001(\rH\003\210\001\001B\007\n\005queryB\007\n\005_txidB" +
      "\024\n\022_query_timeout_secB\t\n\007_splits\")\n\007Quer" +
      "yId\022\016\n\006req_id\030\001 \001(\004\022\016\n\006vip_id\030\002 \001(\004\"l\n\025G" +
      "etQueryStatusRequest\0226\n\010query_id\030\001 \001(\0132$" +
      ".vastdb.queryengine.protocol.QueryId\022\033\n\023" +
      "request_timeout_sec\030\002 \001(\004\"\227\001\n\022FinishQuer" +
      "yRequest\0226\n\010query_id\030\001 \001(\0132$.vastdb.quer" +
      "yengine.protocol.QueryId\022>\n\006reason\030\002 \001(\013" +
      "2).vastdb.queryengine.protocol.Cancellat" +
      "ionH\000\210\001\001B\t\n\007_reason\"\323\002\n\013QueryStatus\0226\n\010q" +
      "uery_id\030\001 \001(\0132$.vastdb.queryengine.proto" +
      "col.QueryId\022.\n\nstart_time\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\0224\n\007metrics\030\003 \003(\0132#.v" +
      "astdb.queryengine.protocol.Metric\0224\n\007tic" +
      "kets\030\004 \003(\0132#.vastdb.queryengine.protocol" +
      ".Ticket\022\030\n\013status_code\030\005 \001(\rH\000\210\001\001\022\030\n\013des" +
      "cription\030\006 \001(\tH\001\210\001\001\022\022\n\005state\030\007 \001(\rH\002\210\001\001B" +
      "\016\n\014_status_codeB\016\n\014_descriptionB\010\n\006_stat" +
      "e\"1\n\010TicketId\022\023\n\013pipeline_id\030\001 \001(\r\022\020\n\010sp" +
      "lit_id\030\002 \001(\r\"k\n\006Ticket\0228\n\tendpoints\030\002 \003(" +
      "\0132%.vastdb.queryengine.protocol.Endpoint" +
      "\022\'\n\tticket_id\030\004 \001(\0132\024.google.protobuf.An" +
      "y\"y\n\022StartQueryResponse\0228\n\006status\030\001 \001(\0132" +
      "(.vastdb.queryengine.protocol.QueryStatu" +
      "s\022\024\n\014arrow_schema\030\002 \001(\014\022\023\n\013is_blocking\030\003" +
      " \001(\010\"R\n\026GetQueryStatusResponse\0228\n\006status" +
      "\030\001 \001(\0132(.vastdb.queryengine.protocol.Que" +
      "ryStatus\"\210\001\n\022ListQueriesRequest\022\033\n\016start" +
      "_time_sec\030\001 \001(\004H\000\210\001\001\022\030\n\013max_entries\030\002 \001(" +
      "\rH\001\210\001\001\022\020\n\003vip\030\003 \001(\tH\002\210\001\001B\021\n\017_start_time_" +
      "secB\016\n\014_max_entriesB\006\n\004_vip\"z\n\023ListQueri" +
      "esResponse\0227\n\tquery_ids\030\001 \003(\0132$.vastdb.q" +
      "ueryengine.protocol.QueryId\022\031\n\014is_trunca" +
      "ted\030\002 \001(\010H\000\210\001\001B\017\n\r_is_truncated\"!\n\006Offse" +
      "t\022\027\n\017record_batch_id\030\001 \001(\004\"\213\002\n\016GetDataRe" +
      "quest\0226\n\010query_id\030\001 \001(\0132$.vastdb.queryen" +
      "gine.protocol.QueryId\022\'\n\tticket_id\030\007 \001(\013" +
      "2\024.google.protobuf.Any\0228\n\006offset\030\003 \001(\0132#" +
      ".vastdb.queryengine.protocol.OffsetH\000\210\001\001" +
      "\022\033\n\023request_timeout_sec\030\004 \001(\004\022\037\n\022respons" +
      "e_size_hint\030\005 \001(\004H\001\210\001\001B\t\n\007_offsetB\025\n\023_re" +
      "sponse_size_hint\"~\n\017GetDataResponse\0226\n\004n" +
      "ext\030\001 \001(\0132#.vastdb.queryengine.protocol." +
      "OffsetH\000\210\001\001\022\031\n\014empty_stream\030\002 \001(\010H\001\210\001\001B\007" +
      "\n\005_nextB\017\n\r_empty_stream\"\277\001\n\021FinishDataR" +
      "equest\0226\n\010query_id\030\001 \001(\0132$.vastdb.querye" +
      "ngine.protocol.QueryId\022\'\n\tticket_id\030\005 \001(" +
      "\0132\024.google.protobuf.Any\022>\n\006reason\030\003 \001(\0132" +
      ").vastdb.queryengine.protocol.Cancellati" +
      "onH\000\210\001\001B\t\n\007_reason\"#\n\014Cancellation\022\023\n\013de" +
      "scription\030\001 \001(\t\"\031\n\tNamespace\022\014\n\004name\030\001 \003" +
      "(\t\"\331\001\n\rSessionOption\022\013\n\003key\030\001 \001(\t\022\026\n\014str" +
      "ing_value\030\002 \001(\tH\000\022\024\n\nbool_value\030\003 \001(\010H\000\022" +
      "\025\n\013int64_value\030\004 \001(\020H\000\022\026\n\014double_value\030\005" +
      " \001(\001H\000\022\025\n\013bytes_value\030\006 \001(\014H\000\022>\n\005scope\030\007" +
      " \001(\0162/.vastdb.queryengine.protocol.Sessi" +
      "onOptionScopeB\007\n\005value\"/\n\016SerializedPlan" +
      "\022\014\n\004plan\030\001 \001(\014\022\017\n\007version\030\002 \001(\t\"\251\001\n\006Metr" +
      "ic\0223\n\003key\030\001 \001(\0132&.vastdb.queryengine.pro" +
      "tocol.Namespace\022\021\n\007counter\030\002 \001(\004H\000\022\017\n\005ga" +
      "uge\030\003 \001(\004H\000\022\023\n\thistogram\030\004 \001(\014H\000\022(\n\004time" +
      "\030\005 \001(\0132\032.google.protobuf.TimestampB\007\n\005va" +
      "lue\"\027\n\010Endpoint\022\013\n\003uri\030\001 \001(\t*4\n\022SessionO" +
      "ptionScope\022\021\n\rUSER_VARIABLE\020\000\022\013\n\007SESSION" +
      "\020\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_QueryEngineGetCapabilitiesResponse_descriptor,
        new java.lang.String[] { "ServerVersion", "SessionOptionsSupport", });
    internal_static_vastdb_queryengine_protocol_StartQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_vastdb_queryengine_protocol_StartQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_StartQueryRequest_descriptor,
        new java.lang.String[] { "Session", "Txid", "Sql", "Substrait", "ComputeIr", "QueryTimeoutSec", "MaxEndpoints", "SupportHa", "Splits", "Query", "Txid", "QueryTimeoutSec", "Splits", });
    internal_static_vastdb_queryengine_protocol_QueryId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_vastdb_queryengine_protocol_QueryId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_QueryId_descriptor,
        new java.lang.String[] { "ReqId", "VipId", });
    internal_static_vastdb_queryengine_protocol_GetQueryStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_vastdb_queryengine_protocol_GetQueryStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_GetQueryStatusRequest_descriptor,
        new java.lang.String[] { "QueryId", "RequestTimeoutSec", });
    internal_static_vastdb_queryengine_protocol_FinishQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_vastdb_queryengine_protocol_FinishQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_FinishQueryRequest_descriptor,
        new java.lang.String[] { "QueryId", "Reason", "Reason", });
    internal_static_vastdb_queryengine_protocol_QueryStatus_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_vastdb_queryengine_protocol_QueryStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_QueryStatus_descriptor,
        new java.lang.String[] { "QueryId", "StartTime", "Metrics", "Tickets", "StatusCode", "Description", "State", "StatusCode", "Description", "State", });
    internal_static_vastdb_queryengine_protocol_TicketId_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_vastdb_queryengine_protocol_TicketId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_TicketId_descriptor,
        new java.lang.String[] { "PipelineId", "SplitId", });
    internal_static_vastdb_queryengine_protocol_Ticket_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_vastdb_queryengine_protocol_Ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_Ticket_descriptor,
        new java.lang.String[] { "Endpoints", "TicketId", });
    internal_static_vastdb_queryengine_protocol_StartQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_vastdb_queryengine_protocol_StartQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_StartQueryResponse_descriptor,
        new java.lang.String[] { "Status", "ArrowSchema", "IsBlocking", });
    internal_static_vastdb_queryengine_protocol_GetQueryStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_vastdb_queryengine_protocol_GetQueryStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_GetQueryStatusResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_vastdb_queryengine_protocol_ListQueriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_vastdb_queryengine_protocol_ListQueriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_ListQueriesRequest_descriptor,
        new java.lang.String[] { "StartTimeSec", "MaxEntries", "Vip", "StartTimeSec", "MaxEntries", "Vip", });
    internal_static_vastdb_queryengine_protocol_ListQueriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_vastdb_queryengine_protocol_ListQueriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_ListQueriesResponse_descriptor,
        new java.lang.String[] { "QueryIds", "IsTruncated", "IsTruncated", });
    internal_static_vastdb_queryengine_protocol_Offset_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_vastdb_queryengine_protocol_Offset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_Offset_descriptor,
        new java.lang.String[] { "RecordBatchId", });
    internal_static_vastdb_queryengine_protocol_GetDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_vastdb_queryengine_protocol_GetDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_GetDataRequest_descriptor,
        new java.lang.String[] { "QueryId", "TicketId", "Offset", "RequestTimeoutSec", "ResponseSizeHint", "Offset", "ResponseSizeHint", });
    internal_static_vastdb_queryengine_protocol_GetDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_vastdb_queryengine_protocol_GetDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_GetDataResponse_descriptor,
        new java.lang.String[] { "Next", "EmptyStream", "Next", "EmptyStream", });
    internal_static_vastdb_queryengine_protocol_FinishDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_vastdb_queryengine_protocol_FinishDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_FinishDataRequest_descriptor,
        new java.lang.String[] { "QueryId", "TicketId", "Reason", "Reason", });
    internal_static_vastdb_queryengine_protocol_Cancellation_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_vastdb_queryengine_protocol_Cancellation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_Cancellation_descriptor,
        new java.lang.String[] { "Description", });
    internal_static_vastdb_queryengine_protocol_Namespace_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_vastdb_queryengine_protocol_Namespace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_Namespace_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_vastdb_queryengine_protocol_SessionOption_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_vastdb_queryengine_protocol_SessionOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_SessionOption_descriptor,
        new java.lang.String[] { "Key", "StringValue", "BoolValue", "Int64Value", "DoubleValue", "BytesValue", "Scope", "Value", });
    internal_static_vastdb_queryengine_protocol_SerializedPlan_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_vastdb_queryengine_protocol_SerializedPlan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_SerializedPlan_descriptor,
        new java.lang.String[] { "Plan", "Version", });
    internal_static_vastdb_queryengine_protocol_Metric_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_vastdb_queryengine_protocol_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_Metric_descriptor,
        new java.lang.String[] { "Key", "Counter", "Gauge", "Histogram", "Time", "Value", });
    internal_static_vastdb_queryengine_protocol_Endpoint_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_vastdb_queryengine_protocol_Endpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vastdb_queryengine_protocol_Endpoint_descriptor,
        new java.lang.String[] { "Uri", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
