/* Copyright (C) Vast Data Ltd. */

// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

public final class JoinKind {
  private JoinKind() { }
  public static final int Anti = 0;
  public static final int Cross = 1;
  public static final int FullOuter = 2;
  public static final int Inner = 3;
  public static final int LeftOuter = 4;
  public static final int LeftSemi = 5;
  public static final int RightOuter = 6;

  public static final String[] names = { "Anti", "Cross", "FullOuter", "Inner", "LeftOuter", "LeftSemi", "RightOuter", };

  public static String name(int e) { return names[e]; }
}

