/* Copyright (C) Vast Data Ltd. */

// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * Limit operation
 */
@SuppressWarnings("unused")
public final class Limit extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Limit getRootAsLimit(ByteBuffer _bb) { return getRootAsLimit(_bb, new Limit()); }
  public static Limit getRootAsLimit(ByteBuffer _bb, Limit obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Limit __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * An identifiier for the relation. The identifier should be unique over the
   * entire plan. Optional.
   */
  public org.apache.arrow.computeir.flatbuf.RelId id() { return id(new org.apache.arrow.computeir.flatbuf.RelId()); }
  public org.apache.arrow.computeir.flatbuf.RelId id(org.apache.arrow.computeir.flatbuf.RelId obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  /**
   * Child relation
   */
  public org.apache.arrow.computeir.flatbuf.Relation rel() { return rel(new org.apache.arrow.computeir.flatbuf.Relation()); }
  public org.apache.arrow.computeir.flatbuf.Relation rel(org.apache.arrow.computeir.flatbuf.Relation obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  /**
   * Starting index of rows
   */
  public long offset() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  /**
   * The maximum number of rows of output.
   */
  public long count() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createLimit(FlatBufferBuilder builder,
      int idOffset,
      int relOffset,
      long offset,
      long count) {
    builder.startTable(4);
    Limit.addCount(builder, count);
    Limit.addOffset(builder, offset);
    Limit.addRel(builder, relOffset);
    Limit.addId(builder, idOffset);
    return Limit.endLimit(builder);
  }

  public static void startLimit(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addRel(FlatBufferBuilder builder, int relOffset) { builder.addOffset(1, relOffset, 0); }
  public static void addOffset(FlatBufferBuilder builder, long offset) { builder.addInt(2, (int)offset, (int)0L); }
  public static void addCount(FlatBufferBuilder builder, long count) { builder.addInt(3, (int)count, (int)0L); }
  public static int endLimit(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // rel
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Limit get(int j) { return get(new Limit(), j); }
    public Limit get(Limit obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

