/* Copyright (C) Vast Data Ltd. */

// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * A single column of literal values.
 */
@SuppressWarnings("unused")
public final class LiteralColumn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static LiteralColumn getRootAsLiteralColumn(ByteBuffer _bb) { return getRootAsLiteralColumn(_bb, new LiteralColumn()); }
  public static LiteralColumn getRootAsLiteralColumn(ByteBuffer _bb, LiteralColumn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LiteralColumn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * The literal values of the column
   */
  public org.apache.arrow.computeir.flatbuf.Literal elements(int j) { return elements(new org.apache.arrow.computeir.flatbuf.Literal(), j); }
  public org.apache.arrow.computeir.flatbuf.Literal elements(org.apache.arrow.computeir.flatbuf.Literal obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int elementsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public org.apache.arrow.computeir.flatbuf.Literal.Vector elementsVector() { return elementsVector(new org.apache.arrow.computeir.flatbuf.Literal.Vector()); }
  public org.apache.arrow.computeir.flatbuf.Literal.Vector elementsVector(org.apache.arrow.computeir.flatbuf.Literal.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createLiteralColumn(FlatBufferBuilder builder,
      int elementsOffset) {
    builder.startTable(1);
    LiteralColumn.addElements(builder, elementsOffset);
    return LiteralColumn.endLiteralColumn(builder);
  }

  public static void startLiteralColumn(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addElements(FlatBufferBuilder builder, int elementsOffset) { builder.addOffset(0, elementsOffset, 0); }
  public static int createElementsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startElementsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endLiteralColumn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // elements
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LiteralColumn get(int j) { return get(new LiteralColumn(), j); }
    public LiteralColumn get(LiteralColumn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

