/* Copyright (C) Vast Data Ltd. */

// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * Projection
 */
@SuppressWarnings("unused")
public final class Project extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Project getRootAsProject(ByteBuffer _bb) { return getRootAsProject(_bb, new Project()); }
  public static Project getRootAsProject(ByteBuffer _bb, Project obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Project __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * An identifiier for the relation. The identifier should be unique over the
   * entire plan. Optional.
   */
  public org.apache.arrow.computeir.flatbuf.RelId id() { return id(new org.apache.arrow.computeir.flatbuf.RelId()); }
  public org.apache.arrow.computeir.flatbuf.RelId id(org.apache.arrow.computeir.flatbuf.RelId obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  /**
   * Child relation
   */
  public org.apache.arrow.computeir.flatbuf.Relation rel() { return rel(new org.apache.arrow.computeir.flatbuf.Relation()); }
  public org.apache.arrow.computeir.flatbuf.Relation rel(org.apache.arrow.computeir.flatbuf.Relation obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  /**
   * Expressions which will be evaluated to produce to
   * the rows of the project relation's output.
   */
  public org.apache.arrow.computeir.flatbuf.Expression expressions(int j) { return expressions(new org.apache.arrow.computeir.flatbuf.Expression(), j); }
  public org.apache.arrow.computeir.flatbuf.Expression expressions(org.apache.arrow.computeir.flatbuf.Expression obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int expressionsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public org.apache.arrow.computeir.flatbuf.Expression.Vector expressionsVector() { return expressionsVector(new org.apache.arrow.computeir.flatbuf.Expression.Vector()); }
  public org.apache.arrow.computeir.flatbuf.Expression.Vector expressionsVector(org.apache.arrow.computeir.flatbuf.Expression.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createProject(FlatBufferBuilder builder,
      int idOffset,
      int relOffset,
      int expressionsOffset) {
    builder.startTable(3);
    Project.addExpressions(builder, expressionsOffset);
    Project.addRel(builder, relOffset);
    Project.addId(builder, idOffset);
    return Project.endProject(builder);
  }

  public static void startProject(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addRel(FlatBufferBuilder builder, int relOffset) { builder.addOffset(1, relOffset, 0); }
  public static void addExpressions(FlatBufferBuilder builder, int expressionsOffset) { builder.addOffset(2, expressionsOffset, 0); }
  public static int createExpressionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startExpressionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endProject(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // rel
    builder.required(o, 8);  // expressions
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Project get(int j) { return get(new Project(), j); }
    public Project get(Project obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

