/* Copyright (C) Vast Data Ltd. */

// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * An unbounded window bound
 */
@SuppressWarnings("unused")
public final class Unbounded extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Unbounded getRootAsUnbounded(ByteBuffer _bb) { return getRootAsUnbounded(_bb, new Unbounded()); }
  public static Unbounded getRootAsUnbounded(ByteBuffer _bb, Unbounded obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Unbounded __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startUnbounded(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endUnbounded(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Unbounded get(int j) { return get(new Unbounded(), j); }
    public Unbounded get(Unbounded obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

