 /*
 *  Copyright (C) Vast Data Ltd.
 */
// this file is auto generated by script/version.py
package com.vastdata.client;

public class VastVersion
{
    public final static int MAJOR = 4;
    public final static int MINOR = 6;
    public final static int PATCH = 0;
    public final static int PROTOCOL = 104;
    public final static String SYS_VERSION = "4.6.0.104";
    public final static String HASH = "a3765c4d2d75d9c6de6b0493ac33292d2c249991";
}
