 /*
 *  Copyright (C) Vast Data Ltd.
 */
// this file is auto generated by script/version.py
package com.vastdata.client;

public class VastVersion
{
    public final static int MAJOR = 5;
    public final static int MINOR = 4;
    public final static int PATCH = 4;
    public final static int PROTOCOL = 0;
    public final static String FEATURES_HASH = "0xb4af7925a4fe5fed";
    public final static String SYS_VERSION = "5.4.4.0.13019758250340278253";
    public final static String HASH = "1e14fabd355e2984876355180953500b154dd7a8";
}
