/* Copyright (C) Vast Data Ltd. */

// automatically generated by the FlatBuffers compiler, do not modify

package vast_flatbuf.tabular;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AlterColumnRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static AlterColumnRequest getRootAsAlterColumnRequest(ByteBuffer _bb) { return getRootAsAlterColumnRequest(_bb, new AlterColumnRequest()); }
  public static AlterColumnRequest getRootAsAlterColumnRequest(ByteBuffer _bb, AlterColumnRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AlterColumnRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String properties() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer propertiesAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer propertiesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String stats() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer statsAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer statsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createAlterColumnRequest(FlatBufferBuilder builder,
      int propertiesOffset,
      int statsOffset) {
    builder.startTable(2);
    AlterColumnRequest.addStats(builder, statsOffset);
    AlterColumnRequest.addProperties(builder, propertiesOffset);
    return AlterColumnRequest.endAlterColumnRequest(builder);
  }

  public static void startAlterColumnRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addProperties(FlatBufferBuilder builder, int propertiesOffset) { builder.addOffset(0, propertiesOffset, 0); }
  public static void addStats(FlatBufferBuilder builder, int statsOffset) { builder.addOffset(1, statsOffset, 0); }
  public static int endAlterColumnRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishAlterColumnRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedAlterColumnRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AlterColumnRequest get(int j) { return get(new AlterColumnRequest(), j); }
    public AlterColumnRequest get(AlterColumnRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

