// automatically generated by the FlatBuffers compiler, do not modify

package vast_flatbuf.tabular;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AlterSchemaRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static AlterSchemaRequest getRootAsAlterSchemaRequest(ByteBuffer _bb) { return getRootAsAlterSchemaRequest(_bb, new AlterSchemaRequest()); }
  public static AlterSchemaRequest getRootAsAlterSchemaRequest(ByteBuffer _bb, AlterSchemaRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AlterSchemaRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String properties() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer propertiesAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer propertiesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createAlterSchemaRequest(FlatBufferBuilder builder,
      int propertiesOffset) {
    builder.startTable(1);
    AlterSchemaRequest.addProperties(builder, propertiesOffset);
    return AlterSchemaRequest.endAlterSchemaRequest(builder);
  }

  public static void startAlterSchemaRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addProperties(FlatBufferBuilder builder, int propertiesOffset) { builder.addOffset(0, propertiesOffset, 0); }
  public static int endAlterSchemaRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishAlterSchemaRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedAlterSchemaRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AlterSchemaRequest get(int j) { return get(new AlterSchemaRequest(), j); }
    public AlterSchemaRequest get(AlterSchemaRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

