// automatically generated by the FlatBuffers compiler, do not modify

package vast_flatbuf.tabular;

public final class ColumnType {
  private ColumnType() { }
  public static final byte Unsorted = 0;
  public static final byte Sorted = 1;

  public static final String[] names = { "Unsorted", "Sorted", };

  public static String name(int e) { return names[e]; }
}

