// automatically generated by the FlatBuffers compiler, do not modify

package vast_flatbuf.tabular;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GetTableStatsResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static GetTableStatsResponse getRootAsGetTableStatsResponse(ByteBuffer _bb) { return getRootAsGetTableStatsResponse(_bb, new GetTableStatsResponse()); }
  public static GetTableStatsResponse getRootAsGetTableStatsResponse(ByteBuffer _bb, GetTableStatsResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetTableStatsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long numRows() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long sizeInBytes() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean isExternalRowidAlloc() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String addressType() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer addressTypeAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer addressTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public vast_flatbuf.tabular.VipRange vips(int j) { return vips(new vast_flatbuf.tabular.VipRange(), j); }
  public vast_flatbuf.tabular.VipRange vips(vast_flatbuf.tabular.VipRange obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int vipsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public vast_flatbuf.tabular.VipRange.Vector vipsVector() { return vipsVector(new vast_flatbuf.tabular.VipRange.Vector()); }
  public vast_flatbuf.tabular.VipRange.Vector vipsVector(vast_flatbuf.tabular.VipRange.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createGetTableStatsResponse(FlatBufferBuilder builder,
      long num_rows,
      long size_in_bytes,
      boolean is_external_rowid_alloc,
      int address_typeOffset,
      int vipsOffset) {
    builder.startTable(5);
    GetTableStatsResponse.addSizeInBytes(builder, size_in_bytes);
    GetTableStatsResponse.addNumRows(builder, num_rows);
    GetTableStatsResponse.addVips(builder, vipsOffset);
    GetTableStatsResponse.addAddressType(builder, address_typeOffset);
    GetTableStatsResponse.addIsExternalRowidAlloc(builder, is_external_rowid_alloc);
    return GetTableStatsResponse.endGetTableStatsResponse(builder);
  }

  public static void startGetTableStatsResponse(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addNumRows(FlatBufferBuilder builder, long numRows) { builder.addLong(0, numRows, 0L); }
  public static void addSizeInBytes(FlatBufferBuilder builder, long sizeInBytes) { builder.addLong(1, sizeInBytes, 0L); }
  public static void addIsExternalRowidAlloc(FlatBufferBuilder builder, boolean isExternalRowidAlloc) { builder.addBoolean(2, isExternalRowidAlloc, false); }
  public static void addAddressType(FlatBufferBuilder builder, int addressTypeOffset) { builder.addOffset(3, addressTypeOffset, 0); }
  public static void addVips(FlatBufferBuilder builder, int vipsOffset) { builder.addOffset(4, vipsOffset, 0); }
  public static int createVipsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVipsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endGetTableStatsResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishGetTableStatsResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedGetTableStatsResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetTableStatsResponse get(int j) { return get(new GetTableStatsResponse(), j); }
    public GetTableStatsResponse get(GetTableStatsResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

