// automatically generated by the FlatBuffers compiler, do not modify

package vast_flatbuf.tabular;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VectorIndexMetadata extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static VectorIndexMetadata getRootAsVectorIndexMetadata(ByteBuffer _bb) { return getRootAsVectorIndexMetadata(_bb, new VectorIndexMetadata()); }
  public static VectorIndexMetadata getRootAsVectorIndexMetadata(ByteBuffer _bb, VectorIndexMetadata obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VectorIndexMetadata __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String columnName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer columnNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer columnNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String distanceMetric() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer distanceMetricAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer distanceMetricInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String sqlFunctionName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sqlFunctionNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer sqlFunctionNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String clusterQuantization() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer clusterQuantizationAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer clusterQuantizationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String searchQuantization() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer searchQuantizationAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer searchQuantizationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public int clusteringProgress() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createVectorIndexMetadata(FlatBufferBuilder builder,
      int column_nameOffset,
      int distance_metricOffset,
      int sql_function_nameOffset,
      int cluster_quantizationOffset,
      int search_quantizationOffset,
      int clustering_progress) {
    builder.startTable(6);
    VectorIndexMetadata.addSearchQuantization(builder, search_quantizationOffset);
    VectorIndexMetadata.addClusterQuantization(builder, cluster_quantizationOffset);
    VectorIndexMetadata.addSqlFunctionName(builder, sql_function_nameOffset);
    VectorIndexMetadata.addDistanceMetric(builder, distance_metricOffset);
    VectorIndexMetadata.addColumnName(builder, column_nameOffset);
    VectorIndexMetadata.addClusteringProgress(builder, clustering_progress);
    return VectorIndexMetadata.endVectorIndexMetadata(builder);
  }

  public static void startVectorIndexMetadata(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addColumnName(FlatBufferBuilder builder, int columnNameOffset) { builder.addOffset(0, columnNameOffset, 0); }
  public static void addDistanceMetric(FlatBufferBuilder builder, int distanceMetricOffset) { builder.addOffset(1, distanceMetricOffset, 0); }
  public static void addSqlFunctionName(FlatBufferBuilder builder, int sqlFunctionNameOffset) { builder.addOffset(2, sqlFunctionNameOffset, 0); }
  public static void addClusterQuantization(FlatBufferBuilder builder, int clusterQuantizationOffset) { builder.addOffset(3, clusterQuantizationOffset, 0); }
  public static void addSearchQuantization(FlatBufferBuilder builder, int searchQuantizationOffset) { builder.addOffset(4, searchQuantizationOffset, 0); }
  public static void addClusteringProgress(FlatBufferBuilder builder, int clusteringProgress) { builder.addByte(5, (byte)clusteringProgress, (byte)0); }
  public static int endVectorIndexMetadata(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VectorIndexMetadata get(int j) { return get(new VectorIndexMetadata(), j); }
    public VectorIndexMetadata get(VectorIndexMetadata obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

