// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Float16Literal extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Float16Literal getRootAsFloat16Literal(ByteBuffer _bb) { return getRootAsFloat16Literal(_bb, new Float16Literal()); }
  public static Float16Literal getRootAsFloat16Literal(ByteBuffer _bb, Float16Literal obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Float16Literal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int value() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }

  public static int createFloat16Literal(FlatBufferBuilder builder,
      int value) {
    builder.startTable(1);
    Float16Literal.addValue(builder, value);
    return Float16Literal.endFloat16Literal(builder);
  }

  public static void startFloat16Literal(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addValue(FlatBufferBuilder builder, int value) { builder.addShort(0, (short)value, (short)0); }
  public static int endFloat16Literal(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Float16Literal get(int j) { return get(new Float16Literal(), j); }
    public Float16Literal get(Float16Literal obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

