// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

public final class IntervalLiteralImpl {
  private IntervalLiteralImpl() { }
  public static final byte NONE = 0;
  public static final byte IntervalLiteralMonths = 1;
  public static final byte IntervalLiteralDaysMilliseconds = 2;

  public static final String[] names = { "NONE", "IntervalLiteralMonths", "IntervalLiteralDaysMilliseconds", };

  public static String name(int e) { return names[e]; }
}

