// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * An identifier for relations in a query.
 *
 * A table is used here to allow plan implementations optionality.
 */
@SuppressWarnings("unused")
public final class RelId extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static RelId getRootAsRelId(ByteBuffer _bb) { return getRootAsRelId(_bb, new RelId()); }
  public static RelId getRootAsRelId(ByteBuffer _bb, RelId obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RelId __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createRelId(FlatBufferBuilder builder,
      long id) {
    builder.startTable(1);
    RelId.addId(builder, id);
    return RelId.endRelId(builder);
  }

  public static void startRelId(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static int endRelId(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RelId get(int j) { return get(new RelId(), j); }
    public RelId get(RelId obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

