// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.computeir.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TimestampLiteral extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static TimestampLiteral getRootAsTimestampLiteral(ByteBuffer _bb) { return getRootAsTimestampLiteral(_bb, new TimestampLiteral()); }
  public static TimestampLiteral getRootAsTimestampLiteral(ByteBuffer _bb, TimestampLiteral obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TimestampLiteral __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long value() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createTimestampLiteral(FlatBufferBuilder builder,
      long value) {
    builder.startTable(1);
    TimestampLiteral.addValue(builder, value);
    return TimestampLiteral.endTimestampLiteral(builder);
  }

  public static void startTimestampLiteral(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addLong(0, value, 0L); }
  public static int endTimestampLiteral(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TimestampLiteral get(int j) { return get(new TimestampLiteral(), j); }
    public TimestampLiteral get(TimestampLiteral obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

