/*
 * Copyright (C) Vast Data Ltd.
 */

package com.vastdata.client;

import com.google.common.collect.ImmutableMap;
import io.airlift.units.DataSize;
import org.testng.annotations.Test;

import java.net.URI;
import java.util.Map;

import static io.airlift.configuration.testing.ConfigAssertions.assertFullMapping;
import static io.airlift.configuration.testing.ConfigAssertions.assertRecordedDefaults;
import static io.airlift.configuration.testing.ConfigAssertions.recordDefaults;

public class TestVastConfig
{
    @Test
    public void testDefaults()
    {
        assertRecordedDefaults(recordDefaults(VastConfig.class)
                .setEndpoint(URI.create("http://localhost:9090"))
                .setDataEndpoints("http://localhost:9090")
                .setRegion("vast")
                .setEnableCustomSchemaSeparator(false)
                .setCustomSchemaSeparator("|")
                .setAccessKeyId(null)
                .setSecretAccessKey(null)
                .setNumOfSplits(1)
                .setNumOfSubSplits(20)
                .setRowGroupsPerSubSplit(8)
                .setQueryDataRowsPerSplit(10485760)
                .setQueryDataRowsPerPage(131072)
                .setAdvisoryPartitionSize(256 * 1024 * 1024)
                .setAdaptivePartitioning(true)
                .setMaxRequestBodySize(5 * 1024 * 1024)
                .setRetryMaxCount(600)
                .setRetrySleepDuration(1000)
                .setParallelImport(true)
                .setMinMaxCompactionMinValuesThreshold(VastConfig.MIN_MAX_COMPACTION_MIN_VALUES_DEFAULT_VALUE)
                .setDynamicFilterCompactionThreshold(VastConfig.DYNAMIC_FILTER_COMPACTION_THRESHOLD_DEFAULT_VALUE)
                .setDynamicFilterMaxValuesThreshold(10000)
                .setDynamicFilteringWaitTimeout(2 * 1000)
                .setDynamicFilteringWaitTimeoutFactor(2)
                .setDynamicFilterElysiumCompactionMultiplier(10)
                .setDynamicFilterPushdownThreshold(99)
                .setPredicatePushdownEnabled(true)
                .setMatchSubstringPushdown(true)
                .setComplexPredicatePushdown(false)
                .setExpressionProjectionPushdown(false)
                .setEnableSortedProjections(true)
                .setOnlyOrderedPushdown(false)
                .setMaxRowsPerInsert(524288)
                .setMaxRowsPerUpdate(65536)
                .setMaxRowsPerDelete(65536)
                .setImportChunkLimit(10)
                .setMaxStatisticsFilesSupportedPerSession(10000)
                .setKeepFilterAfterPushdown(true)
                .setUseColumnHistogram(true)
                .setVastTransactionKeepAliveIntervalSeconds(60)
                .setVastTransactionKeepAliveEnabled(true)
                .setEstimateSplitsFromRowIdPredicate(false)
                .setEstimateSplitsFromElysium(true)
                .setSeedForShufflingEndpoints(null)
                .setCompression("none")
                .setCompressionMinSavings(30)
                .setSplitSizeMultiplier(3)
                .setCompressionLevel(1)
                .setBufferingBufferSizeSoftLimit(DataSize.valueOf("100MB"))
                .setBufferingBufferOpenVsrTargetRowCount(4096)
                .setBufferingBufferOpenVsrRowCountPreallocation(4096)
                .setEngineVersion("NA")
                .setEnableAccessControl(false)
                .setEnableRowColumnSecurity(false)
                .setEnableEndUserImpersonation(false)
                .setPartitionedInsert(true)
                .setMaxInsertBuckets(1000)
                .setInsertPartitionSize(4194304)
                .setInsertExactPartitioning(true)
                .setEnableZeroRowsOptimization(false)
                .setEnablePrefillOptimization(false)
                .setEnableServerStatsCollection(false)
                .setShapingLoggerThreshold(0)
                .setShapingLoggerDuration(io.airlift.units.Duration.valueOf("1m"))
                .setShapingLoggerNumberOfSamples(3)
                .setInsertBufferTargetRowCountPerPartitionFlush(65536)
                .setNodeIoExecutorNumThreads(64)
                .setBufferedInserterMaxWritePermits(64)
                .setBufferedInserterMaxJobPermits(32)
                .setMemoryLimiterMaxAllowed(DataSize.valueOf("100TB"))
                .setEnableMemoryLimit(true)
                .setMemoryLimiterHangingReleasePeriod(io.airlift.units.Duration.valueOf("1m"))
                .setMemoryLimiterHangingValidationInterval(io.airlift.units.Duration.valueOf("1m"))
                .setMemoryLimitMaxNumRunnerFactor(5)
                .setMinRowsForPartitionSplitEstimation(1000000)
                .setReportPartitioning(false)
                .setMetricDumperInterval(io.airlift.units.Duration.valueOf("15m")));
    }

    @Test
    public void testExplicitPropertyMappings()
    {
        Map<String, String> properties = ImmutableMap
                .<String, String>builder()
                .put("endpoint", "file://test.json")
                .put("data_endpoints", "file://test1.json,file://test2.json")
                .put("region", "rrr")
                .put("enable_custom_schema_separator", "true")
                .put("custom_schema_separator", "---")
                .put("access_key_id", "aaa")
                .put("secret_access_key", "zzz")
                .put("num_of_splits", "4")
                .put("num_of_subsplits", "64")
                .put("rowgroups_per_subsplit", "16")
                .put("query_data_rows_per_split", "1024")
                .put("query_data_rows_per_page", "1024")
                .put("advisory_partition_size", "134217728")
                .put("adaptive_partitioning", "false")
                .put("max_request_body_size", "10485760")
                .put("retry_max_count", "3")
                .put("retry_sleep_duration", "30000")
                .put("parallel_import", "false")
                .put("min_max_compaction_min_values_threshold", "300")
                .put("dynamic_filter_compaction_threshold", "2000")
                .put("dynamic_filter_max_values_threshold", "2000")
                .put("dynamic_filtering_wait_timeout", "10000")
                .put("dynamic_filtering_wait_timeout_factor", "4")
                .put("dynamic_filter_elysium_compaction_multiplier", "50")
                .put("dynamic_filter_pushdown_threshold", "100")
                .put("enable_predicate_pushdown", "false")
                .put("match_substring_pushdown", "false")
                .put("complex_predicate_pushdown", "true")
                .put("expression_projection_pushdown", "true")
                .put("enable_sorted_projections", "false")
                .put("only_ordered_pushdown", "true")
                .put("max_row_count_per_insert", "1000")
                .put("max_row_count_per_update", "2000")
                .put("max_row_count_per_delete", "3000")
                .put("import_chunk_limit", "3")
                .put("max_statistics_files_supported_per_session", "5000")
                .put("keep_filter_after_pushdown", "false")
                .put("use_column_histogram", "false")
                .put("vast_transaction_keep_alive_enabled", "false")
                .put("vast_transaction_keep_alive_interval_seconds", "150")
                .put("estimate_splits_from_row_id_predicate", "true")
                .put("estimate_splits_from_elysium", "false")
                .put("seed_for_shuffling_endpoints", "123")
                .put("compression", "zstd")
                .put("compression_min_savings", "40")
                .put("compression_level", "3")
                .put("split_size_multiplier", "30")
                .put("partitioned_insert", "false")
                .put("write-buffering.soft-limit", "33MB")
                .put("write-buffering.partition-flush-target-row-count", "939393")
                .put("write-buffering.open-vsr-row-count-preallocation", "8765")
                .put("write-buffering.open-vsr-target-row-count", "8754")
                .put("write-buffering.max-write-permits", "128")
                .put("write-buffering.max-job-permits", "16")
                .put("engine_version", "1.2.3")
                .put("enable_access_control", "true")
                .put("enable_row_column_security", "true")
                .put("enable_end_user_impersonation", "true")
                .put("max_insert_buckets", "500")
                .put("insert_partition_size", "32")
                .put("insert_exact_partitioning", "false")
                .put("enable_zero_rows_optimization", "true")
                .put("enable_prefill_optimization", "true")
                .put("enable_server_stats_collection", "true")
                .put("shaping_logger_threshold", "50")
                .put("shaping_logger_duration", "10m")
                .put("shaping_logger_number_of_samples", "10")
                .put("node.io-executor.num-threads", "998")
                .put("memory_limiter_max_allowed", "10GB")
                .put("memory_limit_enabled", "false").put("memory_limiter_hanging_validation_interval", "5m")
                .put("memory_limiter_hanging_release_period", "5m")
                .put("memory_limit_max_num_runner_factor", "10")
                .put("min_rows_for_partition_split_estimation", "100")
                .put("report_partitioning", "true")
                .put("metric_dumper_interval", "4m")
                .buildOrThrow();

        VastConfig expected = new VastConfig()
                .setEndpoint(URI.create("file://test.json"))
                .setDataEndpoints("file://test1.json,file://test2.json")
                .setRegion("rrr")
                .setEnableCustomSchemaSeparator(true)
                .setCustomSchemaSeparator("---")
                .setAccessKeyId("aaa")
                .setSecretAccessKey("zzz")
                .setNumOfSplits(4)
                .setNumOfSubSplits(64)
                .setRowGroupsPerSubSplit(16)
                .setQueryDataRowsPerSplit(1024)
                .setQueryDataRowsPerPage(1024)
                .setAdvisoryPartitionSize(134217728)
                .setAdaptivePartitioning(false)
                .setMaxRequestBodySize(10485760)
                .setRetryMaxCount(3)
                .setRetrySleepDuration(30000)
                .setParallelImport(false)
                .setMinMaxCompactionMinValuesThreshold(300)
                .setDynamicFilterCompactionThreshold(2000)
                .setDynamicFilterMaxValuesThreshold(2000)
                .setDynamicFilteringWaitTimeout(10000)
                .setDynamicFilteringWaitTimeoutFactor(4)
                .setDynamicFilterElysiumCompactionMultiplier(50)
                .setDynamicFilterPushdownThreshold(100)
                .setPredicatePushdownEnabled(false)
                .setMatchSubstringPushdown(false)
                .setComplexPredicatePushdown(true)
                .setExpressionProjectionPushdown(true)
                .setEnableSortedProjections(false)
                .setOnlyOrderedPushdown(true)
                .setMaxRowsPerInsert(1000)
                .setMaxRowsPerUpdate(2000)
                .setMaxRowsPerDelete(3000)
                .setImportChunkLimit(3)
                .setMaxStatisticsFilesSupportedPerSession(5000)
                .setKeepFilterAfterPushdown(false)
                .setUseColumnHistogram(false)
                .setVastTransactionKeepAliveEnabled(false)
                .setVastTransactionKeepAliveIntervalSeconds(150)
                .setEstimateSplitsFromRowIdPredicate(true)
                .setEstimateSplitsFromElysium(false)
                .setSeedForShufflingEndpoints(123L)
                .setCompression("zstd")
                .setCompressionMinSavings(40)
                .setSplitSizeMultiplier(30)
                .setCompressionLevel(3)
                .setPartitionedInsert(false)
                .setBufferingBufferOpenVsrTargetRowCount(8754)
                .setBufferingBufferOpenVsrRowCountPreallocation(8765)
                .setBufferingBufferSizeSoftLimit(DataSize.valueOf("33MB"))
                .setBufferedInserterMaxWritePermits(128)
                .setBufferedInserterMaxJobPermits(16)
                .setEngineVersion("1.2.3")
                .setEnableAccessControl(true)
                .setEnableRowColumnSecurity(true)
                .setEnableEndUserImpersonation(true)
                .setMaxInsertBuckets(500)
                .setInsertPartitionSize(32)
                .setInsertExactPartitioning(false)
                .setEnableZeroRowsOptimization(true)
                .setEnablePrefillOptimization(true)
                .setEnableServerStatsCollection(true)
                .setShapingLoggerThreshold(50)
                .setShapingLoggerDuration(io.airlift.units.Duration.valueOf("10m"))
                .setShapingLoggerNumberOfSamples(10)
                .setInsertPartitionSize(32)
                .setInsertBufferTargetRowCountPerPartitionFlush(939393)
                .setNodeIoExecutorNumThreads(998)
                .setMemoryLimiterMaxAllowed(DataSize.valueOf("10GB"))
                .setEnableMemoryLimit(false)
                .setMemoryLimitMaxNumRunnerFactor(10)
                .setMemoryLimiterHangingValidationInterval(io.airlift.units.Duration.valueOf("5m"))
                .setMemoryLimiterHangingReleasePeriod(io.airlift.units.Duration.valueOf("5m"))
                .setBufferedInserterMaxWritePermits(128)
                .setMinRowsForPartitionSplitEstimation(100)
                .setBufferedInserterMaxJobPermits(16)
                .setReportPartitioning(true)
                .setMetricDumperInterval(io.airlift.units.Duration.valueOf("4m"));

        assertFullMapping(properties, expected);
    }
}
